### PR TITLE
Update NCA_Kim2011.py

### PR DESCRIPTION
**Pull request by 1836005678**
Fixing #2744 to make sure we hit the voltage cut-off, instead of the particle stoichiometry going above 1.
Using the function in Kim2011 article to take the place of pybamm\input\parameters\lithium_ion\data\nca_ocp_Kim2011_data.csv for parameter 'Positive electrode OCP[V]' in Kim2011 parameter set.
The function 'nca_ocp_Kim2011(sto)' in pybamm\input\parameters\lithium_ion\NCA_Kim2011.py is edited.

### CODE REVIEW

**Review by tinosulzer — CHANGES_REQUESTED** [review]
Looks good, you just need to remove `import os` in this file since it is no longer used

**Comment by tinosulzer** [comment]
Hmm, tests are failing because the old NCA Kim error was being used to test for the error reporting, if you feel confident to fix it I would suggest adding a different example where the interpolant extrapolates instead. I think something like this should work
```python3
x = np.linspace(0,2)
var = pybamm.Variable("var")
rhs = pybamm.Interpolant(x, x, var, name=name, interpolator="linear")
model = pybamm.BaseModel()
model.rhs[var] = rhs
model.initial_conditions[var] = 1
solver = pybamm.ScipySolver()
t_eval = [0,5]

# solution should grow exponentially and go above var=2, then the interpolant should error
solver.solve(model, t_eval)
```

**Comment by 1836005678** [comment]
Sorry, I don't know what 'old NCA Kim error was being used to test for the error reporting' means. Could you explain it in detail?

**Comment by tinosulzer** [comment]
This test is failing since line 508 expects an error from the parameter set before you fixed it. https://github.com/pybamm-team/PyBaMM/blob/f45f4a5988da047ee356a29fc570475b1a110421/tests/unit/test_solvers/test_casadi_solver.py#L488-L509

Instead, we should test using a standalone piece of code like the one I shared above, and still make sure the error is raised

**Review by tinosulzer — APPROVED** [review]

**Comment by 1836005678** [comment]
Although I still don't quite understand the reason and purpose of this test, I am very grateful for this update and your work.

**Pull request merged**
