### PR TITLE
Split soc and vlimits

### PR DESCRIPTION
**Pull request by js1tr3**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Draft pull request to show changes needed to have separate potentials for 0 and 100 % SOC from the voltage limits used to stop the simulation. This way the simulation of over-charge of over-discharge (to stoichiometry beyond 0 and 100% SOC points can be achieved provided the OCP voltages are defined over the stoich ranges.

Fixes # (issue)

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ flake8`
- [x] All tests pass: `$ python run-tests.py --unit`
- [x] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by tinosulzer** [comment]
Looks like a good start, seems like this should work. Style needs to be fixed so tests can run

**Comment by js1tr3** [comment]
I think I fixed the style issues but haven't figured out how to handle the merge conflict in tutorial 4.

**Comment by tinosulzer** [comment]
Jupyter notebook merges are a nightmare. I would recommend doing `git checkout develop path/to/notebook` to check out the unmerged version to your branch, and then re-make the changes you had made (hopefully not too many)

**Comment by tinosulzer** [comment]
To fix the failing BPX test, add a line around here https://github.com/pybamm-team/PyBaMM/blob/beb8cdffdfaf2b8f96eea1294182408921aebacc/pybamm/parameters/parameter_values.py#L133 to set the "Open circuit potential at ..." equal to "Lower/Upper voltage cut-off" as appropriate.

Also I think it should be "open circuit voltage" when referring to the whole cell

**Comment by tinosulzer** [comment]
@all-contributors add @js1tr3 for code, ideas

**Review by tinosulzer — APPROVED** [review]

**Pull request merged**
