### PR TITLE
Issue 1182 faster tagging for PyBaMM citations 

### LINKED ISSUE #1182: Tag PyBaMM citations
**Summary**
The way citations are printed now (all together) can make it quite hard for an inexperienced user to know why the need to cite each reference. It would be good to add a tag when registering PyBaMM citations and also some extra functionality that, when printing the citations, reads the tags and groups them in a more meaningful way. For example, we could print some sort of list or table that lists:

- Model: Fuller1994
- Parameters: Chen2020
- Solver: Andersson 2019
and so on...

Please add your comments and suggestions

 **Motivation**
 Make it easier for new or inexperienced users to know what's the purpose of each reference, which might lead in them just dumping the citations in their papers all together. Adding this functionality should lead to higher quality citations in the papers.

### PR DESCRIPTION
**Pull request by agriyakhetarpal**
# Description

Enables a faster method to tag citations based on where they come up in the code during a simulation (models, solvers, etc.) – via a `caller_name` method that calls `sys._getframe()` to access current frames for the `pybamm.citations.register()` function. 

This PR continues the discussion on #2862 and #2908, with some results of the speedup available at https://github.com/pybamm-team/PyBaMM/issues/2908#issuecomment-1537077212. Here, `sys._getframe` is preferred to `inspect._getframe()` for avoiding the internal `hasattr()`, in order to reduce any potential performance impact(s) of attribute checks at runtime.

Fixes #1182 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all`
- [x] The documentation builds: `$ python run-tests.py --doctest`

You can run unit and doctests together at once, using `$ python run-tests.py --quick`.

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by agriyakhetarpal** [comment]
@tinosulzer this is a discussion of somewhat different scope, so I am commenting here instead of on the previous thread – I notice that the `pybamm.citations.register()` function is calling itself recursively when it tries to parse the citation with `pybtex` and add it to the `_all_citations` dictionary. This adds to the overhead if a particular model (or solver) registers multiple citations, either explicitly or through its base class due to the use of `super().__init__`. In the earlier profiling results on #2908, it looks like getting the current frame with `_caller_name()` amounts to only a fraction of the total time for `register()` (which just becomes `_caller_name()` + parsing the citations with `pybtex`) – about 30-50% without caching and around 10% if `functools` `@cache` is used with it (if I am thinking about this correctly – I guess this will require some more profiling, with a larger experiment perhaps).

We can move the citation parsing functionality to a new, separate function that only gets called inside `print_citations()`, and keep only the tagging (that cannot be moved outside `register()` since getting the current frame will depend on initialising a model or solver with `register()` at runtime). This way, registering citations would affect performance slightly lesser when solving a model, which is a critical feature. On the other hand, the `print_citations` function will compensate for it and get slightly slower, which should be fine. I am happy to make these changes in this PR itself after further discussion

**Comment by agriyakhetarpal** [comment]
New profiling results: now `_caller_name()` takes more time within `register()` since parsing the citation with `pybtex` has been moved to a separate function `parse_citation()`, which gets called inside `print_citations()` instead

```python
# For the SPM model
%load_ext snakeviz
model = pybamm.lithium_ion.SPM()
sim = pybamm.Simulation(model)
%snakeviz sim.solve([0, 3600])
```

Solving for the first time

image

and solving for the second time (most things get cached)

image

I am unsure why the ncalls are the same here as the previous https://github.com/pybamm-team/PyBaMM/issues/2908#issuecomment-1550213890 though. I am looking for ways to cache `_caller_name()` at the moment, we should not use `@lru_cache` on functions though, so something else must be needed to make this faster.

**Comment by agriyakhetarpal** [comment]
Linking the citation tags hardcoded to their respective models or solvers remains the fastest solution because 1. It does not need to be executed at runtime, and 2. read/write operations to dictionaries or lists within the same file should be very fast

The only disadvantage this has is that it is neither programmatic nor Pythonic

**Comment by agriyakhetarpal** [comment]
Lol the solution to not calling `_caller_name()` was so obvious, but it didn't strike me until now. Just a `try-except` block to not call it if a citation tag already exists 😆

Newer profiling results are much better (the above + parsing registered citations only when printing them): 

<details><summary>DFN</summary>
<p>

```python
# For the DFN model
%load_ext snakeviz
model = pybamm.lithium_ion.DFN()
sim = pybamm.Simulation(model)
%snakeviz sim.solve([0, 3600])
%snakeviz sim.solve([0, 3600])
```

`sim.solve([0, 3600])` first iteration

image

`sim.solve([0, 3600])` second iteration

image

Impact on the DFN model is negligible and it was not impacted in earlier results either, so testing SPM is more important

</p>
</details>

<details><summary>SPM</summary>
<p>

```python
# For the SPM model
%load_ext snakeviz
model = pybamm.lithium_ion.SPM()
sim = pybamm.Simulation(model)
%snakeviz sim.solve([0, 3600])
%snakeviz sim.solve([0, 3600])
```

`sim.solve([0, 3600])` first iteration

image

`sim.solve([0, 3600])` second iteration

image

i.e., never going past ~0.5-0.6% performance impact on any further iterations, was tested by repeating the same code 10 times. 

</p>
</details> 

Do these look good?

**Review by tinosulzer — APPROVED** [review]

**Pull request merged**
