### PR TITLE
#1957 return heat source in isothermal models

### LINKED ISSUE #1957: [Bug]: isothermal model doesn't get heat source terms
### Description

I changed it so that the isothermal models compute the heat source terms using the fixed temperature rather than returning zero, but I forgot to add a `get_coupled_variables` method to `Isothermal` so it currently doesn't calculate anything! Whoops

### Motivation

_No response_

### Possible Implementation

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rtimms**
# Description
Fixes a bug where the isothermal submodel doesn't calculate any heat source terms. There is a new option "calculate heat source for isothermal models" that is "false" by default and "true" otherwise. Default is "false" since this option may require additional parameters not needed by the electrochemical model (specifically current collector parameters).

Fixes #1957 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ flake8`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by brosaplanella — APPROVED** [review]
Looks good! I didn't review the last PR, so is there any tests that checks that the heat source terms are calculated correctly?

**Comment by rtimms** [comment]
Do you mean to test if the variables have the correct expression (i.e. zero or not)? Or some numerical check on the actual values?

**Comment by brosaplanella** [comment]
> Do you mean to test if the variables have the correct expression (i.e. zero or not)? Or some numerical check on the actual values?

I guess both, though just realised I don't know if we are testing this for the other variables anyway haha

**Comment by rtimms** [comment]
> I guess both, though just realised I don't know if we are testing this for the other variables anyway haha

We compare outputs across different models that should be the same and have some tests on variables for things like conservation or checking that things that should be increasing are increasing etc., but we don't test for correct values. 

I'll merge this for now, but maybe we can revisit if there are any useful extra tests on variables.

**Pull request merged**
