### PR TITLE
make initial soc work with half cell models

### LINKED ISSUE #3224: [Bug]: initial_soc not working with half cell model
### PyBaMM Version

23.5

### Python Version

3.10

### Describe the bug

initial_soc not working with half cell model. Works without specifying

### Steps to Reproduce
```
import pybamm

model = pybamm.lithium_ion.SPM({"working electrode": "positive"})
param = pybamm.ParameterValues(("Xu2019"))
experiment = pybamm.Experiment([("Discharge at 1C for 1 hour until 3V",
                                "Charge at 1C for 1 hour until 4.2V",
                                "Hold at 4.2V until 50 mA",
                                "Rest for 30 minutes")])
sim = pybamm.Simulation(model, experiment=experiment, parameter_values=param)
sim.solve(initial_soc=0.5)
sim.plot()
```

### Relevant log output

```shell
Traceback (most recent call last):

  File ~\anaconda3\envs\webapp\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\code\liionpack\tests\unit\untitled0.py:11
    sim.solve(initial_soc=0.5)

  File c:\code\pybamm\pybamm\simulation.py:600 in solve
    self.build_for_experiment(check_model=check_model, initial_soc=initial_soc)

  File c:\code\pybamm\pybamm\simulation.py:422 in build_for_experiment
    self.set_initial_soc(initial_soc)

  File c:\code\pybamm\pybamm\simulation.py:373 in set_initial_soc
    self._unprocessed_parameter_values.set_initial_stoichiometries(

  File c:\code\pybamm\pybamm\parameters\parameter_values.py:256 in set_initial_stoichiometries
    x, y = pybamm.lithium_ion.get_initial_stoichiometries(

  File c:\code\pybamm\pybamm\models\full_battery_models\lithium_ion\electrode_soh.py:570 in get_initial_stoichiometries
    return esoh_solver.get_initial_stoichiometries(initial_value)

  File c:\code\pybamm\pybamm\models\full_battery_models\lithium_ion\electrode_soh.py:471 in get_initial_stoichiometries
    x_0, x_100, y_100, y_0 = self.get_min_max_stoichiometries()

  File c:\code\pybamm\pybamm\models\full_battery_models\lithium_ion\electrode_soh.py:529 in get_min_max_stoichiometries
    Q_n = parameter_values.evaluate(param.n.Q_init)

  File c:\code\pybamm\pybamm\parameters\base_parameters.py:47 in __getattribute__
    raise e

  File c:\code\pybamm\pybamm\parameters\base_parameters.py:19 in __getattribute__
    return super().__getattribute__(name)

AttributeError: 'DomainLithiumIonParameters' object has no attribute 'Q_init'
```

### PR DESCRIPTION
**Pull request by abillscmu**
# Description
Adds methods to use initial soc with half-cell models

Also fixes a spelling mistake I saw, lolz.

@tinosulzer it sounds like is redoing much of this anyway, so this could be considered a hot fix for now given that it may be overwritten soon.

I'd love it if this got into 23.9 as a bug fix so that I don't have to pin to some weird branch waiting for the next version, but understand if that's not possible. If I need to branch off 23.9 to make that happen, I would be happy to do so.

Fixes # (issue)
Fixes #3224 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [x] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by tinosulzer — COMMENTED** [review]
Looks good to me if tests and coverage pass

**Comment by abillscmu** [comment]
Can you run the workflows?

**Comment by abillscmu** [comment]
coverage should be at or very near 100% now

**Review by tinosulzer — APPROVED** [review]

**Comment by Saransh-cpp** [comment]
> I'd love it if this got into 23.9 as a bug fix so that I don't have to pin to some weird branch waiting for the next version, but understand if that's not possible. If I need to branch off 23.9 to make that happen, I would be happy to do so.

Just read this. Adding this into the future rc1 release.

**Pull request merged**
