### PR TITLE
Update Tutorial 4 - Setting parameter values.ipynb

### PR DESCRIPTION
**Pull request by f4try**
Fix bugs in the use of pybamm.Interpolant
------------------------------------------------------------
The init function in interpolant.py is  __init__(self, data, child, name, interpolator, extrapolate, entries_string). So "current_interpolant = pybamm.Interpolant(drive_cycle[:, 0], drive_cycle[:, 1], timescale * pybamm.t)" cause an error showed below. The correct usage should be "current_interpolant = pybamm.Interpolant(drive_cycle,timescale*pybamm.t)".
  
ValueError                 Traceback (most recent call last)
<ipython-input-11-e54986b193b4> in <module>
      6 # Create interpolant
      7 timescale = parameter_values.evaluate(model.timescale)
----> 8 current_interpolant = pybamm.Interpolant(drive_cycle[:, 0], drive_cycle[:, 1], timescale * pybamm.t)
      9 
     10 # Set drive cycle

~/anaconda3/envs/taichi/lib/python3.8/site-packages/pybamm/expression_tree/interpolant.py in __init__(self, data, child, name, interpolator, extrapolate, entries_string)
     41     ):
     42         if data.ndim != 2 or data.shape[1] != 2:
---> 43             raise ValueError(
     44                 """
     45                 data should have exactly two columns (x and y) but has shape {}

ValueError: 
                data should have exactly two columns (x and y) but has shape (601,)

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/master/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [* ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ flake8`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by brosaplanella** [comment]
The `Intepolant` class was recently updated and now it takes x and y separately (that's why the tests in the continuous integration fail). Maybe you ran the updated notebook using the last release and that's why you got the error in the first place.

**Comment by tinosulzer** [comment]
Here is the notebook that will work with the latest pip version: https://github.com/pybamm-team/PyBaMM/blob/master/examples/notebooks/Getting%20Started/Tutorial%204%20-%20Setting%20parameter%20values.ipynb

**Comment by f4try** [comment]
Thank you for your reply. It helps a lot. I will update to the latest version.

**Comment by tinosulzer** [comment]
The "develop" branch is ahead of the latest pip release, so you need to do the "user install" if you want the very latest version. Otherwise you can just keep the pip version and follow the examples in the master branch. We try to keep these breaking changes to a minimum but sometimes they do happen

**Comment by f4try** [comment]
Thank you very much. I just begin to learn PyBaMM. It is great and clear. I will try to use examples in master branch first. I see fuel cells in the roadmap of PyBaMM on Twitter of Nov 24 2020.imageDoes PyBaMM support fuel cell now? Is there any example of PyBaMM on fuel cells?

**Comment by tinosulzer** [comment]
> Does PyBaMM support fuel cell now

Not yet but working on it :)

**Pull request closed without merging**
