### PR TITLE
Don't notify CODEOWNERS on editing the CHANGELOG

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Minor update to save us from notifications

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [ ] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by Saransh-cpp** [comment]
The review on this PR was requested automatically (everything is working).

**Comment by kratman** [comment]
I also noticed that the fine grained way we did it causes duplicate requests. On a different PR "maintainers" were requested, then also multiple individual maintainers.

**Review by agriyakhetarpal — APPROVED** [review]
Thanks, a reminder that we have `towncrier` configuration ready for review in #3469 that will eliminate manual edits to the CHANGELOG

**Comment by Saransh-cpp** [comment]
> On a different PR "maintainers" were requested, then also multiple individual maintainers.

The only situation in which this could happen would be if the files in pybamm/ directory and its subdirectories were modified. We can get rid of this edge case by specifying maintainer usernames here, instead of pybamm-team/maintainers -

https://github.com/pybamm-team/PyBaMM/blob/53793116bd1d5941943d793b6e7e5bcef411dab9/.github/CODEOWNERS#L15

but I guess not a lot of PRs will trigger this. The PR in the screenshot linked by you modifies `CITATION.cff` and a few file in the subdirectories, triggering the edge case.

**Pull request merged**
