### PR TITLE
Make the "partial molar volume" a function of stoichiometry

### PR DESCRIPTION
**Pull request by abillscmu**
# Description
For many chemistries, notably high-nickel NMCs and graphite, the volume change associated with intercalation is a strong function of stoichiometry. Here, I have taken the r-averaged value for Ω and used it to calculate total stress. This accounts for the change without violating the initial model assumptions.

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all`
- [ ] The documentation builds: `$ python run-tests.py --doctest`

You can run unit and doctests together at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by tinosulzer — COMMENTED** [review]
Thanks! 

There is already a parameter, `t_change`, for the electrode thickness change as a function of particle concentration. Should that be the same parameter?

**Comment by abillscmu** [comment]
They are closely related, but not the same. In most cases, `t_change` is a function of `Omega`, but `t_change` is more of a summary variable to monitor volume changes of the cell while `Omega` is used to calculate the stress within a particle. According to Appendix B of Ai 2020 (which based on comments is the paper around which pybamm's stress models are implemented), this is to avoid numerical difficulties.

**Comment by abillscmu** [comment]
I think we could get rid of t_change with this, but it would require us to change the parameter sets to be different from the papers from which they were created.

**Comment by abillscmu** [comment]
Closed in favor of #3576

**Pull request closed without merging**
