### PR TITLE
Return casadi functions

### PR DESCRIPTION
**Pull request by tinosulzer**
# Description

Add functionality to `BaseModel` to export and generate C code from the model. The interface is experimental, likely to change in future

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/master/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ flake8`
- [x] All tests pass: `$ python run-tests.py --unit`
- [x] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by tinosulzer** [comment]
Just need to improve the coverage on this one then we can merge

**Comment by TomTranter** [comment]
Should be good now @tinosulzer

**Comment by tinosulzer** [comment]
Can you approve it so I can merge?

**Review by TomTranter — APPROVED** [review]

**Comment by TomTranter** [comment]
@tinosulzer just a tiny reduction in codecov. Ok to merge?

**Pull request merged**
