### PR TITLE
rewrite full conductivity submodel

### LINKED ISSUE #4324: [Bug]: Half cell negative reaction heating set to 0
### PyBaMM Version

24.5

### Python Version

3.12

### Describe the bug

For some reason reaction heating for the half-cell models is set to 0. As a result, the half-cell models are under calculating heat source (which is important for thermal modeling).

### Steps to Reproduce

Just look at the code: https://github.com/pybamm-team/PyBaMM/blob/fa68ddc0496853b2abf8ef4ef3cdbca88615befc/pybamm/models/submodels/thermal/base_thermal.py#L148 

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by aabills**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #4324 
Enables #4562 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [ ] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by aabills** [comment]
Coverage could be affected here because there are catches for a specific case that this PR eliminates

**Comment by valentinsulzer** [comment]
I'm slightly surprised this works without adding boundary conditions for the internal boundaries but is that already being done by another part of the code?

**Comment by aabills** [comment]
Not explicitly. We do check for accuracy somewhere in tests right? I don't want to merge this without confirming that it is correct.

**Comment by aabills** [comment]
oh yeah, there we go, failing integration tests big time

**Comment by brosaplanella** [comment]
> I'm slightly surprised this works without adding boundary conditions for the internal boundaries but is that already being done by another part of the code?

IIRC this is done in the base class, but only for the concatenated variable (the `composite_conductivity.py` I have been tinkering with didn't have BCs either).

**Comment by aabills** [comment]
> IIRC this is done in the base class, but only for the concatenated variable (the composite_conductivity.py I have been tinkering with didn't have BCs either).

It appears that the code automatically sets Neumann internal boundary conditions for concatenated variables which is not always correct (at least , so that will need to be corrected and I'm guessing will fix this: https://github.com/pybamm-team/PyBaMM/blob/f05cae2ecda531cde049ccfc69d470cdb845bf98/src/pybamm/discretisations/discretisation.py#L339

To handle this, I propose that we should have another dictionary, `internal_boundary_conditions`,  which we check during the code above and default to what the code currently does.

**Pull request closed without merging**
