### PR TITLE
Issue 1575 discharge energy

### LINKED ISSUE #1575: Add Discharged energy [W.h] as variable
**Summary**
Add Discharged energy [W.h] as variable

 **Motivation**
Like discharged capacity but using current * voltage. Useful for performance metrics and minimal overhead

### PR DESCRIPTION
**Pull request by tinosulzer**
# Description

Add "Discharge energy [W.h]" as an output variable (integral of power).
Set option "calculate discharge energy" to "true" to turn on. It's false by default as calculating it can be slow.

Fixes #1575 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ flake8`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by TomTranter** [comment]
@tinosulzer this is a lot of code changes just for one calculation. Did it really slow things down so much to warrant making it an option?

**Comment by tinosulzer** [comment]
Here are the benchmarks with the discharge energy calculation: https://github.com/pybamm-team/PyBaMM/runs/5458023045?check_suite_focus=true

It could probably be done as a post-processing step, with low overhead, but that would be a bigger change

**Comment by tinosulzer** [comment]
It's not that many changes? Most of them are just passing `options` to the external circuit submodels, which we might want to do at some point later anyway

**Comment by TomTranter** [comment]
ok if you think might be useful anyway. I just prefer not having too many options

**Pull request merged**
