### PR TITLE
Use trusted publisher deployment

### PR DESCRIPTION
**Pull request by Saransh-cpp**
# Description

PyPI now allows and encourages uploading files without using any API TOKENS. The trusted publisher deployment can be configured from PyBaMM's PyPI dashboard -

Your account > pybamm > publishing

The tab will look something like this -

image

Environment name should be set to `pypi` while filling in the details, and the workflow should work!

> [!NOTE]  
> The owner account will have to enable 2FA (which should not be an extra overhead, given that 2FA will be mandatory on all PyPI accounts by the end of this year).

### CODE REVIEW

**Comment by brosaplanella** [comment]
I don't have access to it, @tinosulzer do you have access? If not, I can reset the password and set this up.

**Comment by brosaplanella** [comment]
Any update on this? Should I chase for the access details?

**Comment by Saransh-cpp** [comment]
> Should I chase for the access details?

Yes, that would be great. To be on the safer side, we can enable this for `v24.1`.

**Comment by kratman** [comment]
@Saransh-cpp, @brosaplanella Is this still being done for v24.1

**Comment by brosaplanella** [comment]
This has now been approved, so happy to go with it. @Saransh-cpp let me know if you need the credentials to log in.

**Review by agriyakhetarpal — COMMENTED** [review]
Looks good, thanks, @Saransh-cpp and @brosaplanella – this should modify the TestPyPI job too with an accompanying addition of a `testpypi` environment in the repository, in case we need that on some occasion – I have found that pretty useful for some personal projects

**Comment by Saransh-cpp** [comment]
> @Saransh-cpp let me know if you need the credentials to log in.

That would be great, @brosaplanella. I'll be able to update everything in PyPI.

> this should modify the TestPyPI job too with an accompanying addition of a testpypi environment in the repository

maybe sometime after the v24.1 release (or if someone else could take a look at it before the release)

**Comment by agriyakhetarpal** [comment]
Now should be a good time to get this in. Also, to note: the API credentials should be removed from the TestPyPI step as well.

**Comment by kratman** [comment]
@Saransh-cpp, @agriyakhetarpal, @brosaplanella What still needs to be done for this one?

**Comment by agriyakhetarpal** [comment]
The changes in the workflow file are correct, we just need the `pypi` environment set up in the repository settings and the OIDC credentials set up on PyPI

**Comment by Saransh-cpp** [comment]
Ahh, I always forget about this PR. Not this time.

**Comment by Saransh-cpp** [comment]
Okay this should be good to go now (thanks for updating the settings!)

**Comment by agriyakhetarpal** [comment]
> the API credentials should be removed from the TestPyPI step as well

Do we need this, @Saransh-cpp? Both of these uploads are in steps that use the same environment/job, so removing the API keys will break the TestPyPI uploads. We never know when we might require them.

**Comment by kratman** [comment]
> > the API credentials should be removed from the TestPyPI step as well
> 
> Do we need this, @Saransh-cpp? Both of these uploads are in steps that use the same environment/job, so removing the API keys will break the TestPyPI uploads. We never know when we might require them.

I would say we should merge this and then open a new PR to also fix the TestPyPi stuff. That way we have this in place and if we forget the next step the failing test will remind us

**Comment by kratman** [comment]
@agriyakhetarpal I created a ticket for the TestPyPi job

**Pull request merged**
