### PR TITLE
Release v24.5

### PR DESCRIPTION
**Pull request by kratman**
# Description
 
PyBaMM release 24.5

This will be merged into main.

### CODE REVIEW

**Comment by kratman** [comment]
Version is updated, but I did not resolve the conflicts yet. The only changes from RC2 should be the updated version and #4267

**Comment by kratman** [comment]
@agriyakhetarpal, @Saransh-cpp This should be ready for review if anyone wants to check my work. The only changes made during the conflict resolution were due to mistakes in the change log. Some updates that came after 24.1 had their entries entered into the 24.1 section. This corrects it on main for the release, and the sync PR with develop should fix it there.

I created #4291 for other minor stuff that was found, but not worth holding up the release or risking more conflicts. If we find anything else during the testing process we can put it there. So far it was just some mentions of python 3.8 in the installation docs.

**Comment by agriyakhetarpal** [comment]
This looks good to me. Note that the integration tests job is failing in the scheduled tests, while the unit tests pass because the `brew install libomp` command isn't present, I'm not sure if we should aim to fix it here because it's going to run the same tests as the PR tests, which are passing. It's difficult to review the changes from the "Changes" tab on this page because of the sheer size of the diff, but I'm assuming that looking at the comparison between `develop` and `v24.5` at the following link: https://github.com/pybamm-team/PyBaMM/compare/develop...v24.5 should be helpful (and to other reviewers here, too) as to which PRs have been cherry-picked into this branch.

**Comment by kratman** [comment]
@agriyakhetarpal if it helps, this is the diff between this branch and tag v24.5rc2
```
git diff origin/v24.5rc2 --stat
 CHANGELOG.md            |  6 +++---
 CITATION.cff            |  2 +-
 pybamm/util.py          | 22 +++++++++++++++-------
 pybamm/version.py       |  2 +-
 pyproject.toml          |  2 +-
 tests/unit/test_util.py | 15 +++++++++++++++
 vcpkg.json              |  2 +-
 7 files changed, 37 insertions(+), 14 deletions(-)
```

The diff for #4267 is
```
30 insertions(+), 7 deletions(-)
```
The remaining changes should mostly be the version and change log.

**Review by agriyakhetarpal — APPROVED** [review]
Thanks! Sorry, I thought I already approved the PR but I notice I didn't

**Comment by kratman** [comment]
This will also include #4293

**Pull request merged**
