### PR TITLE
remove future imports

### PR DESCRIPTION
**Pull request by tinosulzer**
# Description

Remove all unused future imports

### CODE REVIEW

**Comment by Scottmar93** [comment]
This is my favourite pull request

**Comment by tinosulzer** [comment]
Was very satisfying

**Comment by tinosulzer** [comment]
I don't know, it's also a bit slower using 3.5 than 3.6

**Comment by tinosulzer** [comment]
Also some of the solvers fail to converge with 3.5 (but work fine on 3.6) - https://travis-ci.org/pybamm-team/PyBaMM/jobs/531078575#L3079
Can be fixed by using fewer grid points or stopping at an earlier time, but it's a bit annoying

**Pull request merged**
