### PR TITLE
Fix citations on Colab + bump v22.11.1

### LINKED ISSUE #2543: `pybamm.citations.register` does not work on Google Colab
I have been using PyBaMM for most of 2022 with no issues, but since Google Colab was updated to Python 3.8, I have not been able to run any simulations. 

I have tried the following fixes to no avail:
1. Installed PyBaMM on Colab with `pip install git+https://github.com/pybamm-team/PyBaMM@develop` as suggested by @Saransh-cpp 
- Allows installing/importing  pybamm, but throws an error when defining the model or the parameter_values
- `model = pybamm.lithium_ion.DFN(options={"thermal":"lumped"})` or `parameter_values = pybamm.ParameterValues('Chen2020')`
- Error1: KeyError: 'Not a bibtex citation or known citation: Ai2019'
- Error2: KeyError: 'Not a bibtex citation or known citation: Chen2020'
2. Attempted installation on my local environment (desktop) with `pip install pybamm` 
- Throws an ERROR during installation 
- ERROR: PluginNotFound: plugin pybtex.database.input.bibtex not found
3. Installed PyBaMM on my local environment (desktop) with `pip install git+https://github.com/pybamm-team/PyBaMM@develop`
- Allows installation but throws an ERROR during `import pybamm`
- ERROR: PluginNotFound: plugin pybtex.database.input.bibtex not found

Any other suggestions?

_Originally posted by @renatorod in https://github.com/pybamm-team/PyBaMM/issues/2524#issuecomment-1345971134_

### PR DESCRIPTION
**Pull request by Saransh-cpp**
# Description

Fixes #2543

## Type of change

Adds try-except blocks everywhere the entry points might error out. See the review comments below -

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ flake8`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by Saransh-cpp — COMMENTED** [review]
~This works, but it does not show the users the actual error message. We could instead store the error message and prepend it to the old Google Colab error message. Storing the error message might be helpful if the error message is unrelated to Colab (which we have not seen yet).~

**Comment by Saransh-cpp** [comment]
This works like this right now - https://colab.research.google.com/drive/12JxOESwGl6j9engHG3ASXkk6fT9hWdLQ?usp=sharing. I am not sure if this is the best way to tackle this (the big `if` block in `register` feels weird to me).

I'll update the version strings and changelog (`v22.11.1`) in this PR once everything is finalized. Also, I am not sure if the `tox<4` commit of this PR should be merged to main (needed temporarily to run the tests, I can revert that before merging in).

**Review by brosaplanella — APPROVED** [review]
Looks good, but I don't think you have bumped the version up.

**Comment by Saransh-cpp** [comment]
Done! This would require merging main back to develop, and will most probably generate merge conflicts.

**Review by tinosulzer — APPROVED** [review]
Thanks, looks good to me!

**Pull request merged**
