### PR TITLE
Using `tempfile` for test_symbol_visualise to remove flaky test.

### PR DESCRIPTION
**Pull request by prady0t**
# Description

Using tempfile avoids test failures when running `assert os.path.exists()`

### CODE REVIEW

**Review by Saransh-cpp — COMMENTED** [review]
Why not use the [tmp_path fixture](https://docs.pytest.org/en/stable/how-to/tmp_path.html#the-tmp-path-fixture)? Sorry, I might have missed something.

**Review by kratman — CHANGES_REQUESTED** [review]
The windows failures are caused by the tempfile behavior being a bit different on Windows.

For a bunch of the tests, we do something like this:
```
with tempfile.NamedTemporaryFile(
            suffix=filename, delete=False, mode="w"
        ) as tmp:
```
where the delete=False is what makes it work on windows.

**Comment by agriyakhetarpal** [comment]
Either the Windows fix or using the `tmp_path` fixture sounds good to me. Since the latter is more tied in with `pytest`, I would suggest trying it first.

**Comment by prady0t** [comment]
Thanks for all the suggestions. I've updated the PR

**Review by agriyakhetarpal — APPROVED** [review]

**Pull request merged**
