### PR TITLE
fixed exponent in doc string submesh 1d

### LINKED ISSUE #2226: [Bug]: Equations not displaying properly in docs for 1D submesh
### PyBaMM Version

22.7

### Python Version

3.9

### Describe the bug

https://pybamm.readthedocs.io/en/latest/source/meshes/one_dimensional_submeshes.html

### Steps to Reproduce

https://pybamm.readthedocs.io/en/latest/source/meshes/one_dimensional_submeshes.html

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by dikwickley**
# Description

Changed the equation string in submesh 1d DOC string to show proper exponent

Fixes #2226 

before:
image

after:
image

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ flake8`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by tinosulzer** [comment]
Thanks, @TomTranter is this what you meant with the issue you opened?

**Comment by rtimms** [comment]
Thanks, looks good! Very minor typography point, but can you change the exponential to `\mathrm{e}`?

**Review by TomTranter — CHANGES_REQUESTED** [review]
Thanks for this. Please make the change suggested by @rtimms

**Comment by dikwickley** [comment]
@TomTranter @rtimms i have made the changes

**Comment by tinosulzer** [comment]
need approving review from @TomTranter to merge

**Review by TomTranter — APPROVED** [review]

**Comment by tinosulzer** [comment]
Just noticed style test is failing. Make sure lines are <=88 characters

**Comment by tinosulzer** [comment]
@all-contributors add @dikwickley for code

**Pull request merged**
