### PR TITLE
Removed sd_a- particle size parameters: mean, standard deviation

### LINKED ISSUE #3219: Remove particle size parameters: mean, standard deviation
They are defined in the `GeometricParameters` and `LithiumIonParameters`
https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/parameters/geometric_parameters.py#L113-L115
but not used by any of the models

Having them in is a bit confusing, since changing them does not affect the distribution, which is entirely controlled by `f_a_dist` https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/parameters/size_distribution_parameters.py#L77

A user might think that they can change the distribution by changing one of the mean/sd parameters, but they will have no effect

### PR DESCRIPTION
**Pull request by jeromtom**
# Description
Problem:
Particle size parameters like mean/standard deviation are defined but not used, potentially leading to a situation where the user changes it but it will have no effect

Considerations:
-There isn't one mean standard deviation parameter in [size_distribution_parameter.py](https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/parameters/size_distribution_parameters.py) but sd_p and sd_n for the area-weighted standard deviation of positive and negative electrodes respectively.
-`sd_p` and `sd_n` cannot be directly removed as they are used in the calculations of R_min and R_max which like you said determine the geometry. We can remove to parameter by assigning the default value of 0.3 in the calculations.

Solution:
Removed `sd_a` parameter (area-weighted particle-size standard deviation) from the codebase.

Fixes #3219 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [X] No style issues: `$ pre-commit run` (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [X] All tests pass: `$ python run-tests.py --all`
- [X] The documentation builds: `$ python run-tests.py --doctest`

You can run unit and doctests together at once, using `$ python run-tests.py --quick`.

### CODE REVIEW

**Comment by jeromtom** [comment]
image
I think the docs build failed because I used a special character in the pull request head to highlight that sd_a is a parameter. The local docs build test had passed.

**Comment by jeromtom** [comment]
The linkChecker has failed because of [a timeout](https://github.com/pybamm-team/PyBaMM/actions/runs/5741836094/job/15563838661#step:4:51) from loading/checking one website.

**Review by tinosulzer — COMMENTED** [review]
Looks good, thanks! Can you also remove the mean and standard deviation parameters where they are added to the parameter set in `size_distribution_parameters.py`?

**Review by tinosulzer — APPROVED** [review]
Thanks!

**Comment by jeromtom** [comment]
I think I also have to remove the tests that search for the removed parameter to fix the build checks.
@tinosulzer Kindly confirm

**Comment by tinosulzer** [comment]
Yes, you need to replace them with a test for a different parameter that should be added by `size_distribution_parameters` (e.g. the minimum particle radius)

**Review by tinosulzer — APPROVED** [review]

**Comment by jeromtom** [comment]
Unsuccessful checks:

1. linkChecker: Timeout with the link https://www.rse.ox.ac.uk/ in README.md
2. benchmarks on PR: Originates from a [previously merged PR](https://github.com/pybamm-team/PyBaMM/pull/3228/checks#:~:text=REGRESSIONS%20FOUND,exit%20code%201.)
3. [nox test in Ubuntu 3.10](https://github.com/pybamm-team/PyBaMM/actions/runs/5765926288/job/15634909588?pr=3226#:~:text=ERROR%3A%20THESE%20PACKAGES,exit%20code%201.): This PR does not update the requirements of nox or PyBaMM. If the nox tests were recently updated we have to update the hashes also.

**Pull request merged**
