### PR TITLE
Improve benchmark on push workflow

### LINKED ISSUE #3263: Rationalise benchmark workflows
At the moment a lot of CI time is used by the benchmarks. This is for two main reasons
1. Benchmarks are not killed when a new commit is pushed in that branch (like the tests do).
2. There are 2 benchmark workflows triggered per PR (one on push and one on pull request)

We should rationalise the use of such workflows.

### PR DESCRIPTION
**Pull request by Saransh-cpp**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #3263 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [ ] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by Saransh-cpp** [comment]
The benchmarks running on the first commit were canceled - https://github.com/pybamm-team/PyBaMM/actions/runs/5822608494 - when I pushed the second commit.

**Comment by agriyakhetarpal** [comment]
Lol, I was going to pick this up in #3264 as mentioned on Slack, no worries though 😄

**Review by brosaplanella — APPROVED** [review]
Awesome, thanks Saransh!

**Comment by Saransh-cpp** [comment]
> Lol, I was going to pick this up in #3264 as mentioned on Slack, no worries though 😄

Woops, just saw your message 😅

**Pull request merged**
