### PR TITLE
reduce code duplication in lithium plating notebook

### PR DESCRIPTION
**Pull request by tinosulzer**
# Description

This PR demonstrates how code duplication can be reduced in an example notebook. This makes the notebook significantly easier to maintain.

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ flake8`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by tinosulzer** [comment]
@DrSOKane @RuiheLi

**Comment by DrSOKane** [comment]
This looks really good, please go ahead and merge if the results of the notebook don't change

**Comment by tinosulzer** [comment]
The new ReviewNB plugin allows you to check (by eye) whether the plots have changed, in this case it looks good to me https://app.reviewnb.com/pybamm-team/PyBaMM/pull/2247/

**Comment by DrSOKane** [comment]
Looks good to me also. The markdown still refers to model 1, moel 2 and model 3 even though they're no longer called that, but the models are still defined and run in that order so it should be OK. Great job on reducing the amount of code!

**Review by brosaplanella — APPROVED** [review]
Much clearer now, thanks!

**Pull request merged**
