### PR TITLE
Release v24.5rc1

### PR DESCRIPTION
**Pull request by kratman**
# Description

Release branch for RC1

- [x] Pre-release created
- [ ] Release tested
- [ ] Ready to merge

### CODE REVIEW

**Comment by kratman** [comment]
I will fix the conflicts after the release is done on PyPi

**Comment by kratman** [comment]
Pre-release was created for 0bad87a266ed130c46ffd81fa61c03adbcdc4f0f

**Comment by kratman** [comment]
Failed deployment was testPyPi, the failure should be fixed when I merged develop into this branch

**Comment by kratman** [comment]
@agriyakhetarpal, @Saransh-cpp I did make a mistake here. I am going to do RC2 today, which will be correct

**Comment by agriyakhetarpal** [comment]
No worries, what was the mistake, though?

**Comment by kratman** [comment]
I checked out the 24.5 branch instead of the 24.5rc0 tag. So it already had the rest of develop on there from syncing before the last pre-release branch was merged. Small mistake, but I will make the new release correctly in about an hour

**Comment by agriyakhetarpal** [comment]
I see. Not that it's needed because it's just a release candidate – but @Saransh-cpp or @brosaplanella, could either of you yank the v24.5rc1 release on PyPI with the reason above?

**Comment by kratman** [comment]
I am going to yank it as soon as I login for the day

**Comment by agriyakhetarpal** [comment]
Ah, since you have permissions, please do, thanks!

**Pull request closed without merging**
