### PR TITLE
Add a battery model reference page to the documentation

### PR DESCRIPTION
**Pull request by kratman**
# Description

This change adds a new page with links to battery modeling papers in the fundamentals section of the user guide. When I first went through the tutorials, I noticed that the references were at the end of the notebooks. However, I felt it would have been nice to have easy access to some of the articles before going through the tutorials. This way users, like myself, that are new to battery modeling can download the papers side by side with the tutorials on how to run the models.

Right now the page is only a single paragraph and 6 links, but it can be expanded if other users find it useful. I included two review articles, two lithium-ion battery articles, and two lead-acid battery models.

image

## Type of change

Documentation updates only.

# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [x] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by rtimms — APPROVED** [review]
thanks @kratman , nice idea!

**Comment by kratman** [comment]
This was closed by accident, I restored the branch

**Comment by kratman** [comment]
Sorry, missed that the https://doi.org URLs were ignored by Lychee, but not https://www.doi.org

I think this will pass CI the next round if it is triggered again

**Comment by brosaplanella** [comment]
The lychee error seems unrelated to this PR so merging it.

**Comment by brosaplanella** [comment]
@all-contributors please add @kratman for code (this is for an old PR I forgot to add this)

**Pull request merged**
