### PR TITLE
Remove conditional for scaling of r-R plots

### LINKED ISSUE #2225: [Bug]: Particle size distribution concentration plot x axis may be incorrectly labelled or calculated
### PyBaMM Version

22.7

### Python Version

3.9

### Describe the bug

image

### Steps to Reproduce

```
import pybamm
model = pybamm.lithium_ion.MPM()
sim = pybamm.Simulation(model)
sim.solve([0, 3600])
sim.plot([
    "X-averaged negative particle concentration distribution",
    "X-averaged positive particle concentration distribution",
    "Terminal voltage [V]",
])
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by iatzak**
# Description

Removing hard-coded value of 1 for `first_length_scale` of r-R plots, which made the x axis of these plots be scaled by 1e5.

Fixes #2225 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run`
- [x] All tests pass: `$ python run-tests.py --unit`
- [x] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by tinosulzer — APPROVED** [review]

**Comment by tinosulzer** [comment]
Can you update changelog please?

**Comment by iatzak** [comment]
@tinosulzer I do not understand why such a test ([`test_compare_SPMe_silicon_graphite`](https://github.com/pybamm-team/PyBaMM/blame/develop/tests/integration/test_models/test_full_battery_models/test_lithium_ion/test_compare_outputs_two_phase.py#L161)) fails, given that

1. running `test_compare_outputs_two_phase.py` does not touch the code I modified
2. in the [other workflow run](https://github.com/pybamm-team/PyBaMM/actions/runs/4109147177/jobs/7090652653) (before my changelog commit), this same test passed in macOS (?), but failed in Ubuntu

The error is a convergence fail during an integration in the CasADi solver. This is a very general question, but do you have an idea of what's causing this, considering my change to the code?

**Comment by tinosulzer** [comment]
It's not related to your changes, it's an intermittent test failure that only happens sometimes on GitHub actions and never locally so is really hard to debug. We're just ignoring it for now ...

**Comment by tinosulzer** [comment]
@all-contributors add @iatzak for bugs, code

**Pull request merged**
