### PR TITLE
Update multiprocessing context to be Pool specific

### LINKED ISSUE #3997: [Bug]: PyBaMM fails to import when user has already imported a library that uses `mp.set_start_method`
### PyBaMM Version

develop

### Python Version

3.11

### Describe the bug

PyBaMM fails to import when importing a library that uses multiprocessing and has already set the start method to something other than fork, as a result of #3975. This should be apparent when reading the documentation for `mp.set_start_method`

Pending a long-term solution, I think that #3975 should at least have `mp.set_start_method` wrapped in a try-except -- most people, most of the time, do not really need the multiprocessing functionality, and I don't think pybamm should force those users to modify their multiprocessing configuration. It can throw a warning saying multiprocessing is not available or whatever.

Other solutions are welcome, of course. 
 

### Steps to Reproduce

module `thing`:
```
import multiprocessing as mp

mp.set_start_method("spawn")

def hello():
    print("hello, world")
```

script:
```
import thing
import pybamm
``` 

### Relevant log output

```shell
❯ python main.py 
Traceback (most recent call last):
  File "/Users/abills/.../main.py", line 2, in <module>
    import pybamm
  File "/Users/abills/.../python3.11/site-packages/pybamm/__init__.py", line 204, in <module>
    from .solvers.base_solver import BaseSolver
  File "/Users/abills/.../python3.11/site-packages/pybamm/solvers/base_solver.py", line 18, in <module>
    mp.set_start_method("fork")
  File "/Users/abills/.../python3.11/multiprocessing/context.py", line 247, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

### PR DESCRIPTION
**Pull request by BradyPlanden**
# Description

Convert's the global `mp.set_start_method` context to an individual pool context.

Fixes #3997 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [X] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [X] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [ ] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by BradyPlanden** [comment]
This PR is ready for review. It's a small change to fix #3997. Coverage decreases since we only run the CI on Linux machines, open to suggestions on how to capture the missing line, otherwise it's a small decrease. Not sure a CHANGELOG entry is needed, but happy to add one if so.

**Comment by agriyakhetarpal** [comment]
It's not the best solution as such, but as a stop-gap, you can mark the conditions with a `# pragma: no cover` comment. It is also possible to exclude coverage for just a specific platform, like `# pragma: win32 no cover` – not sure about macOS or Linux, though. For them, I think
```python
# pragma: no cover windows # pragma: no cover macos
```

should work, based on GitHub code search results and [this StackOverflow answer](https://stackoverflow.com/q/41778073/14001839) which works based on specifying these lines in `[tool.coverage]` in `pyproject.toml` (and possibly adding another dependency or two in `[dev]` besides `coverage`).

**Review by kratman — CHANGES_REQUESTED** [review]
@agriyakhetarpal, @BradyPlanden I think a general no-cover is better then adding multiple of them, but there is another solution.

If you make a function that takes platform.system() as an argument, then you can write a test for it.
```python
def get_mp_context(system_type: str):
    if system_type.lower() in ["linux", "darwin"]:
        return "fork"
    return "spawn"

self._mp_context = get_mp_context(platform.system())
```

This requires only a trivial test and is not really any extra complexity or assumptions about coverage.

**Review by valentinsulzer — DISMISSED** [review]
[Removing review - missed Eric's comment]

**Comment by valentinsulzer** [comment]
Wouldn't the `return "spawn"` line still not be covered in the suggested function?

I wonder if we have been over-using "no cover" in the chase for 100% coverage. 99.5 % coverage is fine

**Comment by kratman** [comment]
> Wouldn't the `return "spawn"` line still not be covered in the suggested function?
> 
> I wonder if we have been over-using "no cover" in the chase for 100% coverage. 99.5 % coverage is fine

No because you can write a test for the function I put there. My function is basic input output so the test is just a couple lines:

```python
def test_mp_spawn():
    assert get_mp_context("fake_system") == "spawn"
```

**Comment by kratman** [comment]
> I wonder if we have been over-using "no cover" in the chase for 100% coverage. 99.5 % coverage is fine

In general, I feel 100% coverage usually requires faking coverage in some way:
- Tests on large entry points that don't really "test" anything meaningful
- Pragmas to ignore coverage
- etc

However, there are often simple functions that can be made to make trivial tests. Generally places that need long comments or switches to turn off tests/coverage are code smells that show the code needs to be broken up or refactored

**Review by kratman — APPROVED** [review]

**Pull request merged**
