### PR TITLE
Refactor test_experiment_step_termination.py***

### PR DESCRIPTION
**Pull request by abhicodes369**
(from unit test to pytest)

# Description
converted a unit test case that uses the unit test to pytest. On the official website of pybamm  I saw that they are considering migrating from unit test to pytest.

### CODE REVIEW

**Comment by agriyakhetarpal** [comment]
Thanks for starting this @abhicodes369. It looks good, but ideally we want to do this after #3617, so I will let this sit for a while until that is complete and `pytest` is added to the codebase. If you're interested in contributing, please feel free to discuss something over there since multiple people can be assigned to that issue 🙂

**Comment by agriyakhetarpal** [comment]
@abhicodes369, if you're interested, you can help drive #3857 to completion – or we can take this up again after it gets merged (should be about a week at most).

**Comment by abhicodes369** [comment]
I will look into it

**Review by agriyakhetarpal — APPROVED** [review]
Codacy raises a warning on assert statements despite the fact that it is the recommended way to write `pytest`-style tests and that these are test files. This can be disabled later, some insights here: https://github.com/fossasia/query-server/issues/332

**Review by agriyakhetarpal — APPROVED** [review]

**Comment by agriyakhetarpal** [comment]
@allcontributors please add @abhicodes369 for tests

**Comment by abhicodes369** [comment]
thanks @agriyakhetarpal it really means a lot

**Pull request merged**
