### PR TITLE
Fix failing build wheels

### PR DESCRIPTION
**Pull request by priyanshuone6**
# Description

Fix failing build wheels workflow

Tested on fork
https://github.com/priyanshuone6/PyBaMM/runs/3620734402?check_suite_focus=true

### CODE REVIEW

**Review by brosaplanella — APPROVED** [review]
Thanks Priyanshu!

**Comment by brosaplanella** [comment]
Hi @all-contributors add @priyanshuone6 for PR review and maintenance

**Comment by priyanshuone6** [comment]
Ready to merge!

**Comment by priyanshuone6** [comment]
Really ready now 🤣

**Review by tinosulzer — APPROVED** [review]

**Pull request merged**
