### PR TITLE
Current-driven LAM

### LINKED ISSUE #3252: Implement current depedent LAM
### Description

Add a current dependent LAM model, like the one in eq [26] of [Reniers et al (2019)](https://iopscience.iop.org/article/10.1149/2.0281914jes/pdf)
image

### Motivation

This is another fairly standard LAM model which would be very easy to implement in the framework.

### Possible Implementation

I think for this one it would be good to keep it general and define the RHS of the equation from a parameter function depending on current density and temperature. The user could define the function similarly to what we do with exchange current density so other models can be easily tested.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by brosaplanella**
# Description

Implement current-driven LAM submodel. At the moment it cannot be combined with the other ones, but that's because I wasn't sure how we should set the options (i.e. single string, list of strings...). Happy to leave it as is for the time being or to implement a fix if we agree on a format.

Fixes #3252 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [x] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by tinosulzer** [comment]
Can you add an integration test as well?

**Comment by brosaplanella** [comment]
> Can you add an integration test as well?

For the integration tests I need parameter values, but I don't have any (need to check the Safari & Delacourt paper, but not sure they will translate). Shall I just some dummy parameters (i.e. made up) and define them in place for the integration tests? I want to update the notebook anyway, so I will come up with some parameters for that too.

**Comment by tinosulzer** [comment]
Yes dummy parameters are fine

**Comment by brosaplanella** [comment]
Requesting also @DrSOKane review as I made some changes to the LAM submodels notebook and I believe he was the one who wrote it.

**Review by DrSOKane — CHANGES_REQUESTED** [review]
This new LAM option implements the empirical model of Delacourt and Safari (2012) in PyBaMM. As it is a purely empirical model, I don't see much point in making it compatible with the other LAM models. However, in both the example and the tests, only the linear term of their equation ([26] in Reniers, Mulder and Howey 2019) is included and the nonlinear term is left out. Can you try including the nonlinear term and seeing what happens?

**Review by DrSOKane — APPROVED** [review]

**Comment by tinosulzer** [comment]
Question for @brosaplanella and @DrSOKane : should the minus sign for the current-driven LAM term be in the model or in the parameter?

**Comment by brosaplanella** [comment]
I agree, but thought it would be better to stick to the notation in Reniers et al

**Pull request merged**
