### PR TITLE
Disable benchmarks on PRs

### PR DESCRIPTION
**Pull request by kratman**
# Description

Stop the benchmarks from running on PRs. The reasons for this are the frequent failures and the long runtime. Benchmarks are still run daily and for main/develop

Related: #3662

## Type of change

- [x] Optimization (back-end change that speeds up the code)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [x] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by tinosulzer — APPROVED** [review]

**Comment by agriyakhetarpal** [comment]
I would say that completely stopping benchmark runs is not a good idea in this case. We could fairly easily write a check that skips running benchmarks on PRs by default, but does run them if `[run bench]` exists in the commit message – it won't be too hard to maintain either. A lot of repositories do it and we can document this somewhere in the Testing section of the Contributing guide.

This should be the required one-liner condition (off the top of my head):

```yaml
if: ${{ contains(github.event.head_commit.message, '[run bench]') }}
```

**Comment by kratman** [comment]
> I would say that completely stopping benchmark runs is not a good idea in this case.

They are not stopped completely. They run every day at 3am and run after a PR is merged into main and develop. This only stops them in PRs.

We also have workflows for manual benchmarks. This just speeds it up and stops a frequent failure. I don't think we need to complicated it further by adding extra checks

**Comment by agriyakhetarpal** [comment]
Yes, they aren't stopped completely, but they are disabled on PRs this way. My opinion is that there should be a way to run the benchmarks on a PR if one needs it, through this condition – and making it explicitly stated how to enable them if needed while reasonably keeping defaults to mark them as neutral/skipped (which speeds up the PR checks too as you mentioned)

The manual benchmarks workflow will have to be triggered manually from a branch through the Actions tab, which isn't convenient if you want to experiment with something – this is where commit messages can help

**Comment by agriyakhetarpal** [comment]
Hi @BradyPlanden, please let us know if we can get started on adding a self-hosted runner for the benchmarks (that will now run nightly and for changes from the the `develop` branch's context)

**Pull request merged**
