### PR TITLE
changed dispatch-action for repository-dispatch (#4643)

### LINKED ISSUE #4643: `dispatch-action` is not longer maintained
Use https://github.com/marketplace/actions/repository-dispatch instead of https://github.com/mvasigh/dispatch-action in https://github.com/pybamm-team/PyBaMM/blob/c471f0db7d841033d9edbccd54d19b99d8c70a15/.github/workflows/validation_benchmarks.yml.

### PR DESCRIPTION
**Pull request by AndEsterson**
# Description

Migrates `.github/workflows/validation_benchmarks.yml` from `mvasigh/dispatch-action` to `peter-evans/repository-dispatch`. There are some minor differences in syntax between these two GHAs, which should all be handled by this PR

Fixes #4643 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python -m pytest` (or `$ nox -s tests`)
- [ ] The documentation builds: `$ python -m pytest --doctest-plus src` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ nox -s quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by agriyakhetarpal — APPROVED** [review]
Thanks, @AndEsterson! I would have suggested that we try it on your fork first to confirm the change, but doing it without setting up multiple tokens and repositories/forks is tricky. We could merge this and check if this is adequate, because the workflow is also triggered by pushes to `develop`.

@Saransh-cpp, does this look alright to you?

**Review by Saransh-cpp — APPROVED** [review]
Rechecked validation repo's CI and this should work. Thanks, @AndEsterson!

**Comment by Saransh-cpp** [comment]
@all-contributors please add @AndEsterson for infra

**Comment by Saransh-cpp** [comment]
Ahhh

**Comment by Saransh-cpp** [comment]
Trying this once more, sorry for the extra pings 😬

**Comment by Saransh-cpp** [comment]
@all-contributors please add @AndEsterson for infra

**Comment by AndEsterson** [comment]
thanks everyone for handling the merge! (and for being happy to do it without a full mock setup beforehand 😅 )

**Comment by Saransh-cpp** [comment]
@all-contributors please add @AndEsterson for infra

**Pull request merged**
