### PR TITLE
Fix codecov integration

### PR DESCRIPTION
**Pull request by tlestang**
Attempt to restore code coverage reports.

There was a typo in the code coverage step in the github workflow, causing the code coverage step to never happen.

### CODE REVIEW

**Comment by tlestang** [comment]
I'm just waiting for a coverage report to pop here and I'll merge then.

**Comment by tinosulzer** [comment]
At least it ran: https://codecov.io/gh/pybamm-team/PyBaMM not sure why the bot hasn't posted yet

**Comment by tlestang** [comment]
Because actually there's no code coverage generated anywhere in the workflow (.github/workflow/test_on_push.yaml)! The codecov action just uploads the report, but isnt responsible for generating it.

**Comment by tlestang** [comment]
@tinosulzer Finally back!

**Pull request merged**
