### PR TITLE
Update timeout link in README.md

### LINKED ISSUE #3238: [Bug]: Timeout for link https://www.rse.ox.ac.uk/ in README.md during URL checks
### PyBaMM Version

-

### Python Version

-

### Describe the bug

There is a link in `README.md` that gets a timeout every time the [Lychee URL Checker Test runs](https://github.com/pybamm-team/PyBaMM/actions/runs/5765926282/job/15634894853#:~:text=*%20%5BTIMEOUT%5D%20%5Bhttps%3A//www.rse.ox.ac.uk/%5D(https%3A//www.rse.ox.ac.uk/)%20%7C%20Timeout).

### Steps to Reproduce

Open a PR to trigger the GitHub workflow checks which includes the Lychee URL Checker, you might get an error [like this](https://github.com/pybamm-team/PyBaMM/actions/runs/5765926282/job/15634894853#:~:text=*%20%5BTIMEOUT%5D%20%5Bhttps%3A//www.rse.ox.ac.uk/%5D(https%3A//www.rse.ox.ac.uk/)%20%7C%20Timeout).

### Possible Solutions

1. Formatting the link correctly by removing the last `/` in the link to make it `https://www.rse.ox.ac.uk`.
2. Bypass Lychee from checking this URL, cause this link for Fergus Cooper (@fcooper8472) in the readme works well when you click on the name.

### Relevant log output

```shell
### Errors in README.md

* [TIMEOUT] [https://www.rse.ox.ac.uk/](https://www.rse.ox.ac.uk/) | Timeout


Error: Process completed with exit code 2.
```

### PR DESCRIPTION
**Pull request by jeromtom**
# Description
Excluded the URL  `https://www.rse.ox.ac.uk/` from Lychee URL checks until a permanent solution for the timeout is found.

Fixes #3238

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [X] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [X] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [X] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

### CODE REVIEW

**Comment by agriyakhetarpal** [comment]
I don't think this works since the problem is with the link itself, you may verify it by running Lychee locally:
<details><summary>with `/` at the end of the URL</summary>
<p>
```bash
$ lychee https://www.rse.ox.ac.uk/
[https://www.rse.ox.ac.uk/]:
✗ [ERR] http://rse.ac.uk/ | Failed: Network error: dns error: no record found for Query { name: Name("rse.ac.uk.local."), query_type: AAAA, query_class: IN }
```
</p>
</details> 
<details><summary>without `/` at the end of the URL</summary>
<p>
```bash
$ lychee https://www.rse.ox.ac.uk
[https://www.rse.ox.ac.uk/]:
✗ [ERR] http://rse.ac.uk/ | Failed: Network error: dns error: no record found for Query { name: Name("rse.ac.uk.local."), query_type: AAAA, query_class: IN }
```
</p>
</details>

**Comment by Saransh-cpp** [comment]
Can we increase the timeout time?

**Comment by agriyakhetarpal** [comment]
I don't think the link is timing out, it is a DNS configuration error, rather. We could switch to a different link that would be apt

**Comment by Saransh-cpp** [comment]
> I don't think the link is timing out, it is a DNS configuration error, rather. We could switch to a different link that would be apt

I see. Would changing the endpoints work? Maybe using https://www.rse.ox.ac.uk/about/?

**Comment by agriyakhetarpal** [comment]
No, sub-pages of a website still use the same DNS configuration. We could, however, point to Oxford RSE's GitHub organisation at https://github.com/OxfordRSE and let interested users find their way through there. I was going to suggest their Twitter handle but those don't work well with link checkers either

**Comment by Saransh-cpp** [comment]
Or we could ignore the failure on this link (however that is done in lychee), given that this is a reliable link. I don't have a strong opinion on this, @jeromtom feel free to choose any solution 🙂

**Comment by jeromtom** [comment]
I have excluded this link from Lychee URL checks until we find the root cause and its solution.

**Review by Saransh-cpp — APPROVED** [review]

**Review by agriyakhetarpal — APPROVED** [review]

**Pull request merged**
