### PR TITLE
LFP A123 parameter set

### PR DESCRIPTION
**Pull request by dalbamont**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/master/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ flake8`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by dalbamont** [comment]
LFP cathode files and Severson agreement

**Comment by tinosulzer** [comment]
Thanks @dalbamont , you just need to fix the style in order for the other tests to start. Easiest way to do this is to run "black" https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#black

**Comment by tinosulzer** [comment]
We can close #979, right?

**Comment by tinosulzer** [comment]
Closing this PR and opening a new cleaned one

**Pull request closed without merging**
