### PR TITLE
Adds CODECOV_TOKEN

### PR DESCRIPTION
**Pull request by dalonsoa**
# Description
Adds missing CODECOV_TOKEN to the workflow. Will not work until CODECOV_TOKEN is configured as a Secret in GitHub Actions. 

Fixes # None

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/master/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ flake8`
- [x] All tests pass: `$ python run-tests.py --unit`
- [x] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by dalonsoa** [comment]
I don't think there is. PRs from a forked repo are executed, in practice, in the forked repo, not in the base repo. Apparently, it is a safety measure to avoid someone with ill intentions - outside the collaborators from the repo - from printing the secrets or charge a huge bill (for the case of private repositories, where there's a fee for using GitHub Actions). [This discussion](https://github.community/t/run-a-github-action-on-pull-request-for-pr-opened-from-a-forked-repo/16054) is a bit old, but I think still largely applicable.

**Comment by tinosulzer** [comment]
So will codecov automatically be triggered on the fork, or will there not be codecov on PRs from forks?

**Comment by dalonsoa** [comment]
Actually, it seems we have been doing it wrong all along. There's a [Codecov GitHub Action](https://github.com/codecov/codecov-action) that can be configured and, apparently, it is tokenless.

**Comment by tinosulzer** [comment]
Great, that looks much better! Are you setting it up?

**Comment by dalonsoa** [comment]
Yes... as soon as I figure out where the coverage report is being generated.

**Comment by dalonsoa** [comment]
I've added the Codecov action, but I'm not sure if it will work. I havent' been able to find any coverage report.

**Comment by tinosulzer** [comment]
I had uploaded the wrong token. Shall I try merging this to see what happens?

**Comment by dalonsoa** [comment]
Let’s do it and see what happens, yes. It wont break anything!

________________________________

**Pull request merged**
