### PR TITLE
#2666 put t_+ back inside div, loosen tolerance for test

### LINKED ISSUE #2666: [Bug]: Electrolyte concentration not conserved for non-constant transference number
### PyBaMM Version

23.1

### Python Version

3.8.10

### Describe the bug

The change to full_diffusion.py in PR#2552 fixed lithium conservation for algebraic surface form. However, by moving the migration flux outside the divergence operator, the same fix now violates conservation for the case where transference number is a FunctionParameter, e.g. in the ORegan2022 parameter set.

There must be a general fix that solves this issue for both cases but to solve this issue I would need to learn how the surface form option works and why putting that term inside the divergence operator breaks it.

### Steps to Reproduce

Run any model with the ORegan2022 parameter set and you'll find that "Total lithium [mol]" changes over time

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by tinosulzer**
# Description

Fixes bug introduced that made electrolyte conservation a bit better for constant transference number, but a lot worse for non-constant

Fixes #2666 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all`
- [ ] The documentation builds: `$ python run-tests.py --doctest`

You can run unit and doctests together at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by DrSOKane — COMMENTED** [review]
How does this correct things for the algebraic surface form? Are we just accepting that there will be a some conservation errors in that case?

**Review by DrSOKane — APPROVED** [review]

**Review by brosaplanella — APPROVED** [review]

**Review by brosaplanella — APPROVED** [review]
Thanks! Happy to merge once the ubuntu tests pass (I think they just need to be run again). You need to add a line to the CHANGELOG as well.

**Comment by brosaplanella** [comment]
I think the issue is with one of the getting started notebooks but not sure which one...

**Comment by brosaplanella** [comment]
I think the issue is with one of the getting started notebooks but not sure which one...

**Comment by tinosulzer** [comment]
It works locally for me so hard to debug. Can you test it locally?

**Comment by brosaplanella** [comment]
It looks like the problem is with the [model options notebook](https://github.com/pybamm-team/PyBaMM/blob/develop/examples/notebooks/Getting%20Started/Tutorial%207%20-%20Model%20options.ipynb). I don't know why, but when running it in this branch it gets stuck while in the develop branch it doesn't. Could it be the change in the definition of the flux affecting the heat source terms?

**Comment by DrSOKane** [comment]
It's working fine for me. Have you tried merging the develop branch and running again?

**Comment by brosaplanella** [comment]
> It's working fine for me. Have you tried merging the develop branch and running again?

Which OS are you using? I suspect it might be an Ubuntu issue.

**Comment by DrSOKane** [comment]
> > It's working fine for me. Have you tried merging the develop branch and running again?
> 
> Which OS are you using? I suspect it might be an Ubuntu issue.

Ubunto 20.04 via WSL

**Comment by tinosulzer** [comment]
What's really weird is it also fails in the latexify branch, where I didn't change the model. Made some changes, let's see how it goes

**Comment by brosaplanella** [comment]
Hey @all-contributors, please add @DrSOKane for reviewing PRs

**Comment by brosaplanella** [comment]
@all-contributors, please add @DrSOKane for reviewing PRs

**Pull request merged**
