### PR TITLE
#1927 half-cell thermal models

### LINKED ISSUE #1927: lumped thermal model with half cell
Using a lumped thermal model with half cell gives an error because the options aren't passed to thermal models (so they don't know it's a half cell)

```python3
import pybamm

model = pybamm.lithium_ion.DFN(
    options={
        "working electrode": "positive",
        "thermal": "lumped",
    }
)
```

gives 

```
DomainError: Functions can only be applied to variables on the same domain
```

### PR DESCRIPTION
**Pull request by rtimms**
# Description
Modifies thermal submodels so they work with half-cell models

Fixes #1927 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ flake8`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by tinosulzer — COMMENTED** [review]
There is still an anode in the half-cell, so it will contribute to the thermal problem in the same way as the current collectors do

**Comment by rtimms** [comment]
> There is still an anode in the half-cell, so it will contribute to the thermal problem in the same way as the current collectors do

duh, sorry rushed into this. will fix it properly

**Comment by tinosulzer** [comment]
No worries, would have done the same, only realized it as I was reviewing the PR

**Comment by rtimms** [comment]
> No worries, would have done the same, only realized it as I was reviewing the PR. I guess "cell temperature" and "temperature that goes into the other equations (concentration/potential)" need to be separate variables

Yeah, you get away with it if you're happy with the interpretation that "Cell temperature" is either neg.elec./sep/pos.elec. or sep/work.elec. depending on if you are half-cell or not. But it means you can't use "x-full" with half-cells the way it is currently implemented.

**Review by tinosulzer — APPROVED** [review]
Thanks! We can just figure out x-full later if someone needs it

**Pull request merged**
