### PR TITLE
Updated the `__call__` method

### PR DESCRIPTION
**Pull request by jaskiratsingh2000**
In continuation of PR #2709

### CODE REVIEW

**Comment by rtimms** [comment]
This is missing updating the interpolation function. Please make all the changes in a single PR.

**Comment by jaskiratsingh2000** [comment]
@rtimms Can you let me know that where does I missed the updation of interpolation function? Are you referring to else conditions?

**Comment by tinosulzer** [comment]
I am closing this PR. Push changes to #2709, and we will review that one when its tests pass

**Comment by jaskiratsingh2000** [comment]
Thanks @tinosulzer I made the PR for the same and pushed the commits to #2709 itself.

**Pull request closed without merging**
