### PR TITLE
tests: Use temporary directories in unit tests

### PR DESCRIPTION
**Pull request by kratman**
# Description

The unit tests leave a large number of files behind in the git repo. This change will make the tests use temporary directories when creating files.

I used the tempfile module in python. There are a few other ways to do this, and I believe the preferred method is to use pytest. However, since pytest does not appear to be used, I went with tempfile as the easy solution.

## Type of change

Minor fix in the tests. 

- [x] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [x] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by kratman** [comment]
This will have conflicts with #3373, so it should be reviewed/merged after that one is complete.

**Comment by kratman** [comment]
Conflicts resolved, this should be ready.

**Comment by kratman** [comment]
Lychee error is unrelated to this change

**Comment by kratman** [comment]
@Saransh-cpp Can this be removed so that these files do not keep getting created when I test?

**Comment by Saransh-cpp** [comment]
Sorry for the delay, @kratman, I'll review this before the end of this week. The extra files should not be a problem given that they should be ignored by git? Is there a specific redundant file that is not being ignored in `.gitignore`?

**Comment by kratman** [comment]
None are missed by gitignore, just they exist until I run a cleanup command

**Review by Saransh-cpp — APPROVED** [review]
Thanks for working on this, looks amazing, @kratman!

**Pull request merged**
