### PR TITLE
#383 missing output variable warning

### LINKED ISSUE #383: Warnings for missing required variables
Change the model so that we only give a warning if a user doesn't define any of the required variables. Warning something along the lines of letting users know they might not have defined all the variables required to compare with other models.

### PR DESCRIPTION
**Pull request by rtimms**
# Description

Gives a `pybamm.ModelWarning` if a user leaves a variable as `None`. The `None` entries are then removed from the dictionary as part of `model.check_well_posedness()`.

Fixes #383

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Key checklist:

- [x] No style issues: `$ flake8`
- [x] All tests pass: `$ python run-tests.py --unit`
- [x] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks: 

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by rtimms** [comment]
This seems to work ok on my machine, but is failing on travis with 
```
Traceback (most recent call last):
  File "/home/travis/build/pybamm-team/PyBaMM/tests/unit/test_models/test_base_model.py", line 327, in test_check_well_posedness_output_variables
    with self.assertWarns(pybamm.ModelWarning):
  File "/opt/python/3.5.6/lib/python3.5/unittest/case.py", line 230, in __enter__
    for v in sys.modules.values():
RuntimeError: dictionary changed size during iteration
```

As far as I can tell this is an issue with using `assertWarns`, but I'm not too sure why `sys.modules` is changing size?

**Comment by tinosulzer** [comment]
> This seems to work ok on my machine, but is failing on travis
Weird, can you see if something like 
```python3
with self.assertWarns(...):
    warnings.warn(...)
```
works?

**Comment by martinjrobins** [comment]
This might be a bug in unittest: https://bugs.python.org/issue29620
 
Perhaps you can try the other version of assertWarns: https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertWarns

(the one where the callable is one of the function arguments)

**Comment by rtimms** [comment]
> This might be a bug in unittest: https://bugs.python.org/issue29620
> 
> Perhaps you can try the other version of assertWarns: https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertWarns
> 
> (the one where the callable is one of the function arguments)

Thanks @martinjrobins, this works!

**Pull request merged**
