### PR TITLE
Add parameter list support to JAX solver (permitting multithreading/GPU execution)

### LINKED ISSUE #2644: use massively parallel sundials solvers for running many solves with different input parameters
### Description

Sundials has a few "massively parallel" solvers that can solve many independent models in parallel on a GPU (SUNLinSol_OneMklDense and SUNLinSol_MagmaDense for dense systesm, SUNLinSol_cuSolverSp_batchQR for sparse). These could be used for parameter sweeps, data generation or inference.

See also #2217 

### Motivation

enable the use of GPUs to solver a large number of PyBaMM models in parallel

### Possible Implementation

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jsbrittain**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #2644 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [X] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [X] No style issues: `$ pre-commit run` (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [X] All tests pass: `$ python run-tests.py --all`
- [X] The documentation builds: `$ python run-tests.py --doctest`

You can run unit and doctests together at once, using `$ python run-tests.py --quick`.

## Further checks:

- [X] Code is commented, particularly in hard-to-understand areas
- [X] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by jsbrittain** [comment]
supercedes PR #3028

**Comment by jsbrittain** [comment]
> ## [Codecov](https://app.codecov.io/gh/pybamm-team/PyBaMM/pull/3121?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=pybamm-team) Report
> 
> Patch coverage: **`84.21`**% and project coverage change: **`-0.04`** ⚠️
> 
> > Comparison is base [(`5486fce`)](https://app.codecov.io/gh/pybamm-team/PyBaMM/commit/5486fcecf1b932975721260d3836a9ee5a432807?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=pybamm-team) 99.71% compared to head [(`efc61be`)](https://app.codecov.io/gh/pybamm-team/PyBaMM/pull/3121?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=pybamm-team) 99.68%.
> 
> > ❗ Current head [efc61be](https://github.com/pybamm-team/PyBaMM/commit/efc61be9beae498b737e8653d3c127a5301f7aa1) differs from pull request most recent head [5abff1d](https://github.com/pybamm-team/PyBaMM/commit/5abff1d758b8bb2c7c0fc2ee4b17ef78eff9c268). Consider uploading reports for the commit [5abff1d](https://github.com/pybamm-team/PyBaMM/commit/5abff1d758b8bb2c7c0fc2ee4b17ef78eff9c268) to get more accurate results
> 
> Additional details and impacted files
> 
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/pybamm-team/PyBaMM/pull/3121?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=pybamm-team). 📢 Do you have feedback about the report comment? [Let us know in this issue](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=pybamm-team).

Code coverage is reduced slightly because there are several device specific pathways in the code (gpu vs cpu) that are not currently available for testing in our github CI pipelines.

**Comment by jsbrittain** [comment]
These changes make use of Jax's `vmap` function to distribute solves over a GPU (where available), and multithreading when no GPU is detected. Metrics are for 100 solves with the following model on a ubuntu server with NVIDIA A40 card.
```python
import pybamm
import numpy as np

model = pybamm.lithium_ion.DFN()
model.convert_to_format = 'jax'
model.events = []  # remove events (not supported in jax)
geometry = model.default_geometry
param = model.default_parameter_values
param.update({"Current function [A]": "[input]"})
param.process_geometry(geometry)
param.process_model(model)

n = 10
k = 5
values = np.linspace(0.1, 0.5, 100)
var = pybamm.standard_spatial_vars
var_pts = {var.x_n: n, var.x_s: n, var.x_p: n, var.r_n: k, var.r_p: k}
mesh = pybamm.Mesh(geometry, model.default_submesh_types, var_pts)
disc = pybamm.Discretisation(mesh, model.default_spatial_methods)
disc.process_model(model)
t_eval = np.linspace(0, 3600, 100)
solver = pybamm.JaxSolver(atol=1e-6, rtol=1e-6, method="BDF")
inputs = [{"Current function [A]": value} for value in values]
solution = solver.solve(model, t_eval, inputs=inputs)
```

Solver times:
```
cpu-multithreading: 114 secs
gpu-enabled: 19 secs
```

Further development may be possible by making use of Jax's `pmap` functionality to express single-program multiple-data (SPMD) programs (for running on a rack of GPUs); however, Jax only maintains experimental support for sparse matrices at this time and execution of `pmap` on pybamm models leads to instabilities (see also [https://github.com/google/jax/discussions/13930](https://github.com/google/jax/discussions/13930)).

**Comment by jsbrittain** [comment]
@martinjrobins ready for review. as noted above, code-cov is down very slightly as we do not have github runners checking the gpu-specific implementation pathway. the CI fails seem to be due to apparently unrelated issues with lychee and docs (e.g. ubuntu/python3.11 fails installing doc deps after unit and integration tests all pass). benchmarks also don't appear to be running properly so we may need to delay merging until these are fixed.

**Comment by jsbrittain** [comment]
@martinjrobins I've merged recent develop changes into the PR which has resolved most checks. In particular benchmarks are now passing; this just leaves lychee and my previous codecov comment (gh actions don't check gpu-specific pathways).

**Review by martinjrobins — APPROVED** [review]
Sorry for the delay in reviewing this! Thanks @jsbrittain and happy for it to be merged, I'll open a new issue for adding runners with GPU

**Comment by brosaplanella** [comment]
Can this PR be merged or are we waiting for other changes?

**Comment by jsbrittain** [comment]
> > @brosaplanella Yes, I believe this PR is ready to merge.
> 
> Cool, can you fix the conflict with CHANGELOG and push? Pushing again might also fix the coverage

Note that coverage remains slightly down due to some gpu-specific pathways in the new code; martin opened an issue to support these going forwards (#3274 ).

**Pull request merged**
