### PR TITLE
Fixes breaking changes from #3624

### LINKED ISSUE #4071: [Bug]: `Particle electrode diffusivity` rename breaks ParameterSet.update()
### PyBaMM Version

[Develop]

### Python Version

3.12

### Describe the bug

The parameter rename of `Positive electrode diffusivity` -> `Positive particle diffusivity` currently breaks the `ParameterSet.update()` method.

Linking https://github.com/pybamm-team/PyBaMM/pull/3624

### Steps to Reproduce

```python
import pybamm
parameter_values = pybamm.ParameterValues("Chen2020")
parameter_values.update({"Positive electrode diffusivity [m2.s-1]": 1e-14})
```

### Relevant log output

```shell
{
	"name": "KeyError",
	"message": "\"Cannot update parameter 'Positive electrode diffusivity [m2.s-1]' as it does not have a default value. ('Positive electrode diffusivity [m2.s-1]' not found. Best matches are ['Positive particle diffusivity [m2.s-1]', 'Positive electrode conductivity [S.m-1]', 'Electrolyte diffusivity [m2.s-1]']). If you are sure you want to update this parameter, use param.update({{name: value}}, check_already_exists=False)\"",
	"stack": "---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/Documents/Git/PyBaMM/pybamm/util.py:59, in FuzzyDict.__getitem__(self, key)
     58 try:
---> 59     return super().__getitem__(key)
     60 except KeyError as error:

KeyError: 'Positive electrode diffusivity [m2.s-1]'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
File ~/Documents/Git/PyBaMM/pybamm/parameters/parameter_values.py:247, in ParameterValues.update(self, values, check_conflict, check_already_exists, path)
    246 try:
--> 247     self._dict_items[name]
    248 except KeyError as err:

File ~/Documents/Git/PyBaMM/pybamm/util.py:103, in FuzzyDict.__getitem__(self, key)
    100         raise KeyError(
    101             f\"'{key}' not found. Use the dimensional version '{k}' instead.\"
    102         ) from error
--> 103 raise KeyError(
    104     f\"'{key}' not found. Best matches are {best_matches}\"
    105 ) from error

KeyError: \"'Positive electrode diffusivity [m2.s-1]' not found. Best matches are ['Positive particle diffusivity [m2.s-1]', 'Positive electrode conductivity [S.m-1]', 'Electrolyte diffusivity [m2.s-1]']\"

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[4], line 2
      1 parameter_values = pybamm.ParameterValues(\"Chen2020\")
----> 2 parameter_values.update({\"Positive electrode diffusivity [m2.s-1]\": 1e-14})

File ~/Documents/Git/PyBaMM/pybamm/parameters/parameter_values.py:249, in ParameterValues.update(self, values, check_conflict, check_already_exists, path)
    247         self._dict_items[name]
    248     except KeyError as err:
--> 249         raise KeyError(
    250             f\"Cannot update parameter '{name}' as it does not \"
    251             + f\"have a default value. ({err.args[0]}). If you are \"
    252             + \"sure you want to update this parameter, use \"
    253             + \"param.update({{name: value}}, check_already_exists=False)\"
    254         ) from err
    255 # if no conflicts, update
    256 if isinstance(value, str):

KeyError: \"Cannot update parameter 'Positive electrode diffusivity [m2.s-1]' as it does not have a default value. ('Positive electrode diffusivity [m2.s-1]' not found. Best matches are ['Positive particle diffusivity [m2.s-1]', 'Positive electrode conductivity [S.m-1]', 'Electrolyte diffusivity [m2.s-1]']). If you are sure you want to update this parameter, use param.update({{name: value}}, check_already_exists=False)\""
}
```

### PR DESCRIPTION
**Pull request by BradyPlanden**
# Description

This PR updates `ParameterSet.update()` and `Solver.solve()` so that #3624 is non-breaking.

Fixes #4071 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [X] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [x] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by kratman** [comment]
Out of curiosity, if we did the renaming of the parameter, where is the old name coming from in PyBaMM usage?

In #4071 it looks like you manually passed the old name into the function. Is there another tool in the PyBaMM ecosystem that is still using the old name?

**Comment by BradyPlanden** [comment]
Fair question. The previous name would be used in any script/notebook/package built before v24.5, and in those cases, if `ParameterSet.update()` or `Solver.solve(inputs={old_name:value})` is called, the change would be breaking. #3624 both renames the parameter and does the conversion in the [FuzzyDict](https://github.com/pybamm-team/PyBaMM/blob/fadf094d17d0562319e4d5065a2eee1a9848b004/pybamm/util.py#L60), but misses the above methods. This PR fixes that.

**Comment by kratman** [comment]
I know we have deprecation warnings for the parameter name changes, I think if anything we should update them to catch it better. Putting it is the base solver seems like the wrong approach. Once we are out of the deprecation window then we would expect to be able to remove the code checking for it.

**Comment by BradyPlanden** [comment]
> Putting it is the base solver seems like the wrong approach. Once we are out of the deprecation window then we would expect to be able to remove the code checking for it.

I agree it's not a very clean solution, but given the `inputs` arg is a user defined dictionary and directly passed from user-level I don't believe we can catch it before that point. Unless you see an alternative?

How do we track removal of depreciation warnings at the moment? Perhaps adding depreciation warnings around the additions in this PR and adding them to a log for removal after two release would ensure they get removed when ready.

**Comment by brosaplanella** [comment]
We discussed about deprecation warnings in https://github.com/pybamm-team/PyBaMM/issues/2028 a while ago, but not much progress has been made.

**Comment by valentinsulzer** [comment]
Can you share the scripts that are broken on `develop` and work with this fix?

**Comment by kratman** [comment]
Summary of my comments from the meeting: "Can the check for the old parameter name be done only in the update function and add a warning"

**Comment by BradyPlanden** [comment]
> Can you share the scripts that are broken on develop and work with this fix?

Sure @valentinsulzer, [any of these](https://github.com/pybamm-team/PyBaMM/tree/develop/docs/source/examples/notebooks/parameterization) with the old parameter name used in `parameter_values.update()` or the inputs object for `solve()` will break in develop and be fixed by this PR. It's any time `ParameterSet.update({name:value})` or `solver.solve(input={name:value})` uses the previous parameter name, both of which are used throughout the examples.

> "Can the check for the old parameter name be done only in the update function and add a warning"
Yep, I'll sort this and drop a line once it's ready for review.

**Comment by valentinsulzer** [comment]
Nice preview of how painful it is to rename a parameter, for you guys leading the parameter refactor effort

**Review by brosaplanella — APPROVED** [review]
Looks good to me, thanks! It would be good to get a second review, just for a second opinion on how to handle the warnings. BTW, could you add a line to the CHANGELOG?

**Comment by BradyPlanden** [comment]
There are a few tests that are failing periodically at the moment, but it seems to be across the repo. For coverage, the lines in question are being missed periodically, but not as a function of this PR. This should be good for the final review now.

**Pull request merged**
