### PR TITLE
Type of Driving Cycle ('A', 'V', 'W') in Experiment Class

### PR DESCRIPTION
**Pull request by alibh95**
# Description

The experiment.py file is modified to read the operating conditions string which includes the type of driving cycle ('A', 'V', 'W').
This change is suggested by @tinosulzer in #1193. 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ flake8`
- [x] All tests pass: `$ python run-tests.py --unit`
- [x] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by Saransh-cpp** [comment]
Hi @alibh95, I was also working on this issue and most of the code in this PR is almost the same (even better I'd say) as the one I added in my local files, one addition that I had that is missing here was a value error for the user if the type of data is not specified. Something like this - 
```py
raise ValueError(
                    """type of data provided using a drive cycle should be
                    specified using 'A', 'V' or 'W'.
                    For example: {}
                    """.format(
                        examples
                    )
                )
```
Maybe we can add something like this?

As, for example, if an experiment `Run US06` is simulated, the code gives an error  -
```terminal
typ = cond_list[2][1]
IndexError: list index out of range
```
because of the absence of a specifier like `(A)`

**Comment by alibh95** [comment]
@tinosulzer to create an interpolant in the experiment class, we have to pass the model into it. 
As the model is already passed into the simulation class. I think it would be better to create interpolant in that class.

**Comment by alibh95** [comment]
@Saransh-cpp I didn't know that you were also working on this part of #1193. That's a great suggestion to raise error if the type of driving cycle is not provided.

**Comment by tinosulzer** [comment]
Ok - good point about where you can define the interpolant. In that case you should also store the time points to pass to the simulation so it can create the interpolant

**Comment by alibh95** [comment]
@tinosulzer Kindly review this PR.

**Review by tinosulzer — APPROVED** [review]
Thanks @alibh95 , merging

**Pull request merged**
