### PR TITLE
[WIP] updates for BPX v0.4.0 compatibility 

### LINKED ISSUE #3679: `ParameterValues.create_from_bpx` - support BPX v0.4
### Description

Add support to `ParameterValues.create_from_bpx()` for new [BPX 0.4](https://bpxstandard.com/bpx-standard/) features.

- Import blended electrode parameters according to specification.
- Consider whether PyBaMM could define a standard for importing user-defined parameters for model extensions. As an example, this might include a read from BPX for the necessary branches for `current sigmoid` hysteresis from user-defined BPX `FloatFunctionTable` features.

### Motivation

_No response_

### Possible Implementation

A simple PyBaMM-internal standard might be that the contents of the BPX user-defined parameters node is read directly into the `ParameterValues` object. Then users could add any PyBaMM-compatible parameter names to the BPX, under this node.

Since the content of a BPX file implies the type of model that should be used (DFN vs SPM, blended electrode or not, hysteresis or not), could `create_from_BPX` optionally return a `dict` of appropriate model options? Or else another utility function could do this?

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rtimms**
# Description
Add support for blended electrodes and user-defined parameters in BPX. Create parameters from BPX file in a loop using `partial`.

PyBaMM now requires `bpx>=0.4.0`

Note: BPX set initial concentrations based on SOC, which is not yet supported in pybamm for blended electrodes (see  https://github.com/pybamm-team/PyBaMM/issues/2682). If a user supplies a "blended electrode" BPX file then they must manually provide initial concentrations after the `ParameterValues` class has been created (or supply them in the "user-defined" section).

Fixes #3679 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [ ] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by Saransh-cpp — COMMENTED** [review]
@rtimms ideally no new features (and especially no new breaking changes) should be added to a release after the release candidate is out. I think we should not add this to v24.1, given that this is not a bug fix.

**Comment by rtimms** [comment]
@Saransh-cpp ok, thanks, let’s leave this out

**Comment by rtimms** [comment]
there is new functionality in BPX v0.4 that won’t work with pybamm until this is merged, so we should either merge this or pin BPX < 0.4

this isn’t a huge breaking change in that is immediately fixed by updating the BPX version. 

thoughts?

**Review by brosaplanella — APPROVED** [review]
Looks good, my main coverage is that coverage needs to be improved. Happy either for this to make it in the release or waiting until 24.5 (and pinning version for this release).

**Pull request merged**
