### PR TITLE
Release v24.5rc2

### PR DESCRIPTION
**Pull request by kratman**
# Description

Release branch for RC1

- [x] Pre-release created
- [ ] Release tested
- [ ] Ready to merge

### CODE REVIEW

**Comment by Saransh-cpp** [comment]
I think this PR can be closed. Something went wrong with the GitHub steps and we should not go directly from rc0 to rc2 in git history for the develop branch.

**Comment by kratman** [comment]
@Saransh-cpp other way around. I made the rc1 release with a mistake, yanked it, and then made rc2

**Comment by kratman** [comment]
When v24.5 was merged into develop, all of develop was merged into that branch. This one is cherry picked directly on top of the rc0 tag. The mistake in RC1 was that I created it with the v24.5 branch, which was not the same as rc0.

Once rc2 was tested, I was going to fix the v24.5 branch to make it match

**Comment by Saransh-cpp** [comment]
Yes, I went through the branches and releases. The three branches have started diverging, which is causing conflicts. We yanked the `rc1` release but I think it should still be present in the git history, given that we did make a release (and it is on our GitHub as well). The additional conflicts from this branch are also an issue.

Merging the rc1 changes into develop first and then the rc2 ones would make all the conflicts/branch divergences go away.

**Comment by kratman** [comment]
@Saransh-cpp, @brosaplanella, @agriyakhetarpal I am going to sync this with develop so it can be merged. Then I will delete the branch after.

The v24.5 branch will be updated to the v24.5rc2 tag

**Review by Saransh-cpp — CHANGES_REQUESTED** [review]
I think you'll have to rebase and resolve the conflicts.

**Review by brosaplanella — APPROVED** [review]

**Review by Saransh-cpp — APPROVED** [review]
Thanks for working on this, @kratman!

**Pull request merged**
