### PR TITLE
Create CITATION.cff

### LINKED ISSUE #1574: Add citation.cff
https://twitter.com/natfriedman/status/1420122675813441540

### PR DESCRIPTION
**Pull request by priyanshuone6**
# Description

Create CITATION.cff

Fixes #1574 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ flake8`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by tinosulzer — APPROVED** [review]
Add ORCID IDs:
Valentin Sulzer https://orcid.org/0000-0002-8687-327X 
Scott G. Marquis https://orcid.org/0000-0002-6895-990X

**Review by tinosulzer — APPROVED** [review]

**Comment by tinosulzer** [comment]
Oops. I merged too quickly, weren't we also goign to update the journal?

**Comment by brosaplanella** [comment]
Yes, we should try if it is possible

**Comment by priyanshuone6** [comment]
I have already added it

**Comment by tinosulzer** [comment]
It doesn't show up in the citation :( I guess github doesn't support it

**Comment by Saransh-cpp** [comment]
https://github.com/Parsl/parsl, https://github.com/citation-file-format/citation-file-format these repositories have a working citations tab. I think the version specified in .cff file should be the version of cff i.e. 1.1.0 (https://github.com/citation-file-format/citation-file-format/releases/tag/1.1.0)

**Pull request merged**
