### PR TITLE
#1140 fix EC SEI bug

### LINKED ISSUE #1140: Repeated entry
The last entry in this dictionary of `base_sei.py` is repeated. It looks that the last one is missing the units. I guess it should be [mol.m-3], but I'm not entirly sure.

https://github.com/pybamm-team/PyBaMM/blob/c320ad7700211606e53ccfe3ac867d30c495b9c5/pybamm/models/submodels/interface/sei/base_sei.py#L173-L185

### PR DESCRIPTION
**Pull request by tinosulzer**
# Description

Fixes the units for a variable in the EC SEI submodel

Fixes #1140 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/master/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ flake8`
- [x] All tests pass: `$ python run-tests.py --unit`
- [x] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by ferranbrosa — APPROVED** [review]
Good catch, thanks Tino!

**Review by dalonsoa — APPROVED** [review]
👍

**Comment by tinosulzer** [comment]
@all-contributors add @ferranbrosa for pull requests

**Comment by tinosulzer** [comment]
@all-contributors add @ferranbrosa for reviewed pull requests

**Comment by tinosulzer** [comment]
@all-contributors add @ferranbrosa for review

**Comment by tinosulzer** [comment]
@all-contributors add @dalonsoa  for review

**Pull request merged**
