### PR TITLE
Remove notebook outputs from main directory

### PR DESCRIPTION
**Pull request by kratman**
# Description

The notebook **solution-data-and-processed-variables.ipynb** left some files behind [outputs.csv, outputs.mat, outputs.pickle]. These files were missed in #3377 

## Type of change

Minor fix, does not break anything.

- [x] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [x] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by kratman** [comment]
Sorry for force pushing, something went wrong when I tried to do a cleanup change

**Review by brosaplanella — APPROVED** [review]
Looks good, thanks!

**Comment by kratman** [comment]
Benchmark failure is unrelated, should be good to go

**Comment by brosaplanella** [comment]
This is a small change affecting the examples, so leaving it to @Saransh-cpp if he wants to merge now or wait until the release candidate is published.

**Comment by Saransh-cpp** [comment]
Sorry, just saw this. Merging, thanks @kratman!

**Pull request merged**
