### PR TITLE
#614 reorganise model docs

### LINKED ISSUE #614: Reformat model docs
Make it clearer which models are implemented

### PR DESCRIPTION
**Pull request by tinosulzer**
# Description

Reorganise model docs to make it clearer which models are used by PyBaMM.
note:
- this branch merges into #608  to make use of the options documentation
- I think we can now get rid of the example models (reaction diffusion and simple ODE) as they don't add anything beyond the examples in the examples folder. Reaction-diffusion in particular is annoying to maintain (#615)

Fixes #614

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Key checklist:

- [x] No style issues: `$ flake8`
- [x] All tests pass: `$ python run-tests.py --unit`
- [x] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks: 

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by rtimms** [comment]
will have a proper look tomorrow, but looks good. one comment: should we add refs for the li-ion models (e.g. to Scott's paper) and then in the blurb in the models docs we can say each of the pre-built models contains a ref with the model docstring?

**Comment by tinosulzer** [comment]
I think the failing tests are because #608 is failing so will leave this until that is merged

**Comment by rtimms** [comment]
isn't this being merged into #608? I'm not sure on how merging into other PRs works - do you have to merge this into 608 and then that into master, or does merging 608 into master take this along with it?

**Comment by tinosulzer** [comment]
Thought #608 was also failing hence why this was failing, but looks like it's fine now.
Either order works - if we merge this into 608 first then the 608 PR will include these changes, whereas if we merge 608 into master first then (I think) this branch will merge directly into master afterwards. So go ahead and merge 608 if it's ready

**Comment by tinosulzer** [comment]
@rtimms @Scottmar93 any ideas why there's that error with the DFN example? I haven't changed anything in the code specific to it

**Comment by rtimms** [comment]
looks like #550 is failing on the same thing. this happened once before on master -- the PR was passing all tests, then after merge master was failing this notebook. but then a different PR got merged and everything was passing again, so I presumed whatever bug it was had been inadvertently fixed. weird, as #550 was passing all the tests before, and like you, nothing specific to that example has been changed...

**Pull request merged**
