### PR TITLE
Algolia docsearch

### PR DESCRIPTION
**Pull request by agriyakhetarpal**
# Description

This PR adds Algolia DocSearch v3 since our application was accepted recently. Third-party search functionality is not supported with PyData Sphinx Theme yet (https://github.com/pydata/pydata-sphinx-theme/issues/202, https://github.com/pydata/pydata-sphinx-theme/issues/795

Therefore, manual templates are added along with the [`sphinx-docsearch`](https://github.com/algolia/sphinx-docsearch) extension from Algolia to render the search bar. This disables the default search bar.

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all`
- [x] The documentation builds: `$ python run-tests.py --doctest`

You can run unit and doctests together at once, using `$ python run-tests.py --quick`.

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by agriyakhetarpal** [comment]
**Some updates:** there are definitely ways to make Algolia work with the PyData Sphinx Theme—the `sphinx-docsearch` extension is just a wrapper and does the same thing as adding the necessary JavaScript files in `html_js_files`, Algolia's custom CSS in `html_css_files`, and overrides the search button template at the time the Sphinx builder performs the initialisation. Here are some references of how some other libraries' documentation websites built with PST add the search box – all of them use the same, manual process: 

1. [sgkit documentation](https://pystatgen.github.io/sgkit/latest/) (slightly off-set position, they override the fullscreen overlay)
2. [Orchest documentation](https://orchest.readthedocs.io/en/stable/index.html) (they simply add their own search field in the navbar with PyData's search icon. We can remove the search icon)
3. [DeterminedAI documentation](https://docs.determined.ai/latest/reference/overview.html) (they have their own colour scheme and have customised their theme extensively, but their location is in the left sidebar and it works)
4. [Deepchecks documentation](https://docs.deepchecks.com/0.17/getting-started/welcome.html) (they seem to align the Algolia overlay pretty well to 'join' the navbar just above it)

There seems to be a `require.js` error in our case both locally and on readthedocs, when I try to follow their build processes (it should work out of the box using the above solution of adding the JavaScript and CSS files) so I probably need to investigate. I filed an [issue](https://discourse.algolia.com/t/problems-setting-up-algolia-docsearch-v3-with-sphinx-documentation-on-read-the-docs/18612) in the Algolia forum on Discourse to seek help and will follow up on any responses I receive.

**Comment by agriyakhetarpal** [comment]
This should be ready for review/merge now once tests pass—apparently the error about `require.js` came from `nbsphinx` and is used to load interactive widgets in the notebooks `ipywidgets` and also happens to break a lot of other Sphinx extensions that rely on JavaScript. This explains https://github.com/pybamm-team/PyBaMM/issues/3165#issuecomment-1645755973, so we now know why the rendered notebooks won't display sliders in the docs, but I think it is a minor compromise since users can download the notebooks anyway or run them in Colab.

I also added a few CSS customisations so that the elements resemble the PyData Sphinx Theme. The new, blazing-fast search can be tried here: https://pybamm--3159.org.readthedocs.build/en/3159/

**Review by Saransh-cpp — APPROVED** [review]
That's super fast! Thanks for working on this, @agriyakhetarpal!

**Comment by agriyakhetarpal** [comment]
Before we merge this I just want to make sure that the position is correct on smaller screens and try it on a Windows system which uses <kbd>Ctrl</kbd> instead of <kbd>⌘</kbd> in the search box

**Comment by Saransh-cpp** [comment]
Sounds good, let us know when this is ready to merge.

**Comment by agriyakhetarpal** [comment]
Good to go now!

**Pull request merged**
