### PR TITLE
Prepare release 21.11

### PR DESCRIPTION
**Pull request by brosaplanella**
# Description

Prepare `develop` for the new release 21.11.  A few things left to do before merging:

- [ ] Update `vcpkg-configuration.json` baseline (@priyanshuone6 can you point me to the right commit ID please?)
- [ ] Update CHANGELOG: are there any of the open PRs we want to bring in before releasing @tinosulzer?
- [ ] Jax: there is still the version issue (#1625), is it OK to keep the versions as they are?

### CODE REVIEW

**Review by tinosulzer — APPROVED** [review]
No urgent PRs to merge

**Comment by priyanshuone6** [comment]
All the jax tests are passing with the current pinned versions I guess we can keep the jax versions as they are

**Comment by priyanshuone6** [comment]
Updated the sdist action as `Publish sdist on pypi` step was getting skipped
https://github.com/pybamm-team/PyBaMM/runs/4094768383?check_suite_focus=true

**Comment by brosaplanella** [comment]
We need to reopen this one as I need to update the CHANGELOG

**Pull request merged**
