### PR TITLE
Issue #2649 Installed sphinxcontrib-bibtex for bibtex style referencing

### LINKED ISSUE #2649: Change hard-coded refs in docstrings to sphinxcontrib-bibtex
https://sphinxcontrib-bibtex.readthedocs.io/en/latest/index.html

### PR DESCRIPTION
**Pull request by jeromtom**
# Description
This is the first step to start using sphinxcontrib-bibtex to show references/citations from bibtex instead of hardcoding them in docstrings.

It starts by installing sphinxcontrib-bibtex as per sphinxcontrib-bibtex documentation:
https://sphinxcontrib-bibtex.readthedocs.io/en/latest/quickstart.html#installation

Changes:
1.   Add sphinxcontrib-bibtex extension to docs/conf.py (Sphinx configuration file) and point the reference file
2.   Created a file refs.bib with the entry for authors (Data taken from the CITATION.cff file)
3.  Updated the hard-coded references/citations to sphinxcontrib-bibtex code.

This is can be considered as a part of the upcoming GSOC 2023: Documentation Infrastructure Project.

Fixes #2649 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [X] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by tinosulzer** [comment]
The relevant citations file is in https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/CITATIONS.txt

An example of a hard-coded citation to be replaced by a bibtex reference is https://github.com/pybamm-team/PyBaMM/blob/a3756ded80f4436f0a763785afa21c36a15dc8ea/pybamm/input/parameters/lithium_ion/Chen2020.py#L11-L14

**Comment by tinosulzer** [comment]
Thanks @jeromtom . Can you delete the `CITATIONS.txt` since `refs.bib` is now duplicate. Will require making updates where `CITATIONS.txt` is called

**Comment by Saransh-cpp** [comment]
@jeromtom you will have to fix the merge conflicts.

**Comment by jeromtom** [comment]
I have doubts if sphinx-contrib BibTeX supports the `pybamm.citations.register()` function and don't know what to modify.

**Comment by tinosulzer** [comment]
What are you trying to do? `sphinx-contrib` and `pybamm.citations.register()` are two separate things. Both call the same citations bib file. But they do different things. `sphinx-contrib` is for docs. `register()` is for python code.

**Comment by jeromtom** [comment]
@tinosulzer, I am trying to fix this kind of error
`
FAIL: test_timms_2021 (test_citations.TestCitations)
Traceback (most recent call last):
File "C:\Users\jerto\Documents\GitHub\PyBaMM\tests\unit\test_citations.py", line 153, in test_timms_2021
self.assertIn("2021:Timms2021", citations._papers_to_cite)
AssertionError: '2021:Timms2021' not found in set()`

Traced this particular one to
        `citations._reset() 
         self.assertNotIn("2021:Timms2021", citations._papers_to_cite) 
         pybamm.current_collector.BasePotentialPair(param=None)
         self.assertIn("2021:Timms2021", citations._papers_to_cite)`

**Comment by tinosulzer** [comment]
That's because you changed the names of the citations (e.g. Timms2021 to 2021:Timms2021). Is there a reason you did that?

**Comment by tinosulzer** [comment]
Fixed in #3034

**Pull request closed without merging**
