### PR TITLE
Spherical finite volume

### PR DESCRIPTION
**Pull request by tinosulzer**
# Description

Fixes a bug in `finite_volumes.py` for spherical diffusion.
`(r_edge[i+1]**3 - r_edge[i]**3)/3` is now used instead of `r_node**2`. This is what it should be according to Finite Volume theory e.g. https://journals.aps.org/prapplied/abstract/10.1103/PhysRevApplied.6.064010

Screen Shot 2021-11-03 at 3 48 05 PM

Previous convergence: 

Figure_2

New convergence:

Figure_1

Code: 
```python3
import pybamm
import numpy as np

model = pybamm.lithium_ion.DFN()

chemistry = pybamm.parameter_sets.Ecker2015
parameter_values = pybamm.ParameterValues(chemistry=chemistry)

var = pybamm.standard_spatial_vars
npts = [10, 20, 25, 30, 40, 50]

solver = pybamm.CasadiSolver(mode="safe")
t_eval = np.linspace(0, 3800, 200)

sols = []
for N in npts:
    var_pts = {var.x_n: 20, var.x_s: 20, var.x_p: 20, var.r_n: N, var.r_p: N}
    sim = pybamm.Simulation(
        model,
        solver=solver,
        parameter_values=parameter_values,
        var_pts=var_pts,
        # C_rate=5,
    )
    sol = sim.solve(t_eval=t_eval)
    print("N={}: {} s".format(N, sol.solve_time))
    sols.append(sol)

pybamm.dynamic_plot(sols, ["Terminal voltage [V]"], time_unit="seconds", labels=npts)
```

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ flake8`
- [x] All tests pass: `$ python run-tests.py --unit`
- [x] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by tinosulzer** [comment]
Since the convergence is better, we could reduce the default number of r points to 20 (10 still gives inaccurate results at higher C-rates). See #1075

**Review by rtimms — APPROVED** [review]
Thanks, @tinosulzer , nice catch! This has been lurking for a while...

Yes, let's reduce the default points, and maybe we can also check to see if we can now use fewer points in [this notebook](https://github.com/pybamm-team/PyBaMM/blob/develop/examples/notebooks/models/simulating-ORegan-2021-parameter-set.ipynb)? I'm guessing we might be able to since the method is correct now.

**Review by brosaplanella — APPROVED** [review]
Looks good, thanks Tino!

**Comment by tinosulzer** [comment]
How did you come up with 150 points for the ORegan parameter set
before:
Figure_2

now:
Figure_1
?

**Comment by brosaplanella** [comment]
There were some issues with the convergence with the low diffusion areas, but maybe with the final parameter set is not needed any more. If it converges, happy to reduce the number of points 😄

**Pull request merged**
