### PR TITLE
Discover Parameter Sets using Entry Points

### PR DESCRIPTION
**Pull request by awadell1**
# Description

Enables pybamm to discover parameter sets via the `pybamm_parameter_set` entry point:

- Third parties can now distribute parameter sets (via python packages) that are automatically detected by PyBamm
- Enables a decentralized approach to parameter sharing
- External parameter sets can be version controlled

As a bonus, updated `pybamm.Citations` to support registering BibTex strings, as external parameter sets don't have access to `pybamm/CITATIONS.txt`

cfcb589: This is mostly superseded by c2be58d, which uses jinja + `pybamm.parameter_sets.get_docstring` to generate the docstrings for all parameter sets. On the plus side, this supports all the fun sphinx documentation features. The downside the current doc strings are not formatted as reStructuredText. I'm happy to fix that but wanted to get the ball rolling first.

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [X] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ flake8`
- [x] All tests pass: `$ python run-tests.py --unit`
- [x] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by awadell1** [comment]
@tinosulzer Can we make `all_parameter_sets` private as `pybamm.parameter_sets` implements the dict interface?

if so, we can replace change this:
https://github.com/pybamm-team/PyBaMM/blob/58879c82c7678198a76052b00566c5d09bf8a9a4/examples/scripts/print_model_parameter_combinations.py#L8

To:
```python
all_parameter_sets = [k for k,v in pybamm.parameter_sets.items() if v["chemistry"] == "lithium_ion"]
```

Probably also need to update the docs for [Adding Parameter Values](https://github.com/pybamm-team/PyBaMM/blob/58879c82c7678198a76052b00566c5d09bf8a9a4/docs/tutorials/add-parameter-values.rst) to:
- Remove depreciated mixing of parameter sets #2342
- Remove depreciated dot access to parameter sets `pybamm.parameter_sets.Marquis2019`
- Encourage new parameter sets to be added via entry points, and not contributions to PyBamm

**Comment by awadell1** [comment]
@tinosulzer Can we make `pybamm.parameter_sets.all_parameter_sets` internal, as `pybamm.parameter_sets` implements the dict interface? 

Then we can change this: 
https://github.com/pybamm-team/PyBaMM/blob/58879c82c7678198a76052b00566c5d09bf8a9a4/examples/scripts/print_model_parameter_combinations.py#L8

To this: 

```python
 all_parameter_sets = [k for k,v in pybamm.parameter_sets.items() if v["chemistry"] == "lithium_ion"]
```

Probably need to update: https://github.com/pybamm-team/PyBaMM/blob/58879c82c7678198a76052b00566c5d09bf8a9a4/docs/tutorials/add-parameter-values.rst
- Remove depreciated dot access: pybamm.parameter_sets.Marquis2019 (Depreciated in #2342)
- Remove mix and matching of parameter values (Depreciated in #2342)
- Remove references to add new parameters via PRs, in favor of adding them via new packages (This PR)

**Review by tinosulzer — APPROVED** [review]
Looks good, merging

**Comment by tinosulzer** [comment]
@all-contributors add @awadell1 for code, tests, docs

**Pull request merged**
