### PR TITLE
Update vcpkg-configuration

### PR DESCRIPTION
**Pull request by priyanshuone6**
# Description

- Update vcpkg-configuration
- Add vcpkg in release-checklist
- Add fail-fast in workflow

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ flake8`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by tinosulzer** [comment]
Can you make this a PR to main?

**Review by tinosulzer — APPROVED** [review]
merge in #1644 to fix the macos tests

**Comment by priyanshuone6** [comment]
Oops, I think you already merged #1644, I'll revert the commit `Merge branch 'pybamm-team:develop' into vcpkg`

**Comment by tinosulzer** [comment]
Yeah you need to undo the last merge and only merge the `test_on_push.yml` changes (or just manually change those files yourself)

**Comment by priyanshuone6** [comment]
@tinosulzer All these commits from this PR will be merged to the main branch but not the develop branch, will we create a new PR from main to develop to merge these commits to develop?

**Comment by tinosulzer** [comment]
Yeah let's do that after. Can you remove the changes to plotting too, since they aren't in the 21.08 release on github?

**Pull request merged**
