### PR TITLE
add more points to OKane OCP data

### PR DESCRIPTION
**Pull request by tinosulzer**
# Description

Add more points to the "extrapolation" section of the OCP for OKane2022. This fixes some weird nonlinearity that was breaking the esoh solver

Before: 
Figure_1

After: Figure_1

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ flake8`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by tinosulzer** [comment]
@DrSOKane just checking this makes sense

**Review by brosaplanella — APPROVED** [review]
Looks good, thanks!

**Comment by DrSOKane** [comment]
This is a good idea but I'm wondering on what basis that extrapolation was chosen. Some measurements of graphite OCP have it going all the way to zero at x=1, while others have it remain finite.

**Comment by tinosulzer** [comment]
I don't know how it was chosen, but I didn't change that, only added linearly spaced points

**Pull request merged**
