### PR TITLE
simplify nondimensionalisation of kinetics

### PR DESCRIPTION
**Pull request by tinosulzer**
# Description

Simplifies non-dimensionalisation of the kinetics, which I think was making things overly complicated.

Previously, `j0` was calculated as =
```python
j0 = gamma * j0(...) / C_r
```
but
Screen Shot 2022-08-16 at 5 24 10 PM

and we are currently scaling `j0(...)` as `j0(...) = j0_dim(...) / j0_ref`, so 

```python
j0 = gamma * j0_dim(...) / j0_ref / C_r = j0_dim(...) / j_scale
```

and if instead we scale `j0(...) = j0_dim(...) / j_scale` then

```python
j0 = j0(...)
```

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ flake8`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by tinosulzer** [comment]
just sanity checking

Screen Shot 2022-08-17 at 5 40 21 PM

**Review by brosaplanella — APPROVED** [review]
Looks good, thanks @tinosulzer!

**Comment by brosaplanella** [comment]
BTW, should we set a deprecation warning for the unused constants with the deprecated package?

**Comment by tinosulzer** [comment]
> BTW, should we set a deprecation warning for the unused constants with the deprecated package?

the parameters are still there, so where were you thinking of adding the warning?

Also I have no idea why that test is failing, and only on python 3.7

**Comment by brosaplanella** [comment]
Yes, not too fussed about the test.

I mean that, if the dimensionless numbers are not used, we might want to get rid of them eventually. If so, we can use deprecated to fail at a given release so we remove it.

**Pull request merged**
