### PR TITLE
3937 events with idaklu output variables - solver edit

### LINKED ISSUE #3937: [Bug]: output variables option in idaklu solver fails when event triggered
### PyBaMM Version

24.1

### Python Version

3.10

### Describe the bug

When the output_variables option of the IDAKLU solver is used in a simulation with an event, the solve fails with the error message below when trying to get the event reason

### Steps to Reproduce

```python
def test(solver):
    model = pybamm.lithium_ion.DFN()
    parameter_values = pybamm.ParameterValues("Chen2020")

    sim = pybamm.Simulation(
        model,
        parameter_values=parameter_values,
        solver=solver,
    )
    sol = sim.solve(np.linspace(0, 3600, 1000))
    sol = sol["Terminal voltage [V]"].entries

test(pybamm.IDAKLUSolver(output_variables=["Terminal voltage [V]"]))
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/mrobins/git/tmp/test.py", line 17, in <module>
    test(pybamm.IDAKLUSolver(output_variables=["Terminal voltage [V]"]))
  File "/home/mrobins/git/tmp/test.py", line 14, in test
    sol = sim.solve(np.linspace(0, 3600, 1000))
  File "/home/mrobins/git/tmp/env/lib/python3.10/site-packages/pybamm/simulation.py", line 584, in solve
    self._solution = solver.solve(self.built_model, t_eval, **kwargs)
  File "/home/mrobins/git/tmp/env/lib/python3.10/site-packages/pybamm/solvers/base_solver.py", line 959, in solve
    solutions[i], termination = self.get_termination_reason(
  File "/home/mrobins/git/tmp/env/lib/python3.10/site-packages/pybamm/solvers/base_solver.py", line 1303, in get_termination_reason
    final_event_values[event.name] = event.expression.evaluate(
  File "/home/mrobins/git/tmp/env/lib/python3.10/site-packages/pybamm/expression_tree/binary_operators.py", line 132, in evaluate
    right = self.right.evaluate(t, y, y_dot, inputs)
  File "/home/mrobins/git/tmp/env/lib/python3.10/site-packages/pybamm/expression_tree/binary_operators.py", line 132, in evaluate
    right = self.right.evaluate(t, y, y_dot, inputs)
  File "/home/mrobins/git/tmp/env/lib/python3.10/site-packages/pybamm/expression_tree/binary_operators.py", line 132, in evaluate
    right = self.right.evaluate(t, y, y_dot, inputs)
  File "/home/mrobins/git/tmp/env/lib/python3.10/site-packages/pybamm/expression_tree/symbol.py", line 778, in evaluate
    return self._base_evaluate(t, y, y_dot, inputs)
  File "/home/mrobins/git/tmp/env/lib/python3.10/site-packages/pybamm/expression_tree/state_vector.py", line 284, in _base_evaluate
    raise ValueError(
ValueError: y is too short, so value with slice is smaller than expected
(env) ➜  tmp pip list |grep pybamm
```

### PR DESCRIPTION
**Pull request by pipliggins**
# Description

This is an alternative to #4150 (old pull request will be closed)

Simulations using the IDAKLU solver with output variables specified which terminated with an event rather than the final time step would crash trying to find the termination event.

Termination events are found in the Solution class by using the state vector of the final time-step to evaluate each potential termination event and find the minimum (the event which caused the termination). When output variables are specified in the IDAKLU solver only those variables are output in `y_out`, not the entire state vector, so the events could not be evaluated outside the solver.

This PR edits the IDAKLU solver to add an additional return value containing the state vector for the final timestep only ('y_term') when output variables are specified. This value is used to fill the `Solution.y_event` attribute and allows termination events to be calculated as normal, while not impacting the performance advantages of selecting only a few output variables. When output variables are not specified, this returns an empty array as it copies part of the provided state vector.

Fixes #3937 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [x] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by pipliggins** [comment]
As mentioned in the previous PR (https://github.com/pybamm-team/PyBaMM/pull/4150#discussion_r1639840070), specifying output variables in the IDAKLU solver doesn't currently work with experiments. This bug fix should enable that behaviour to be added, but I think it should be a separate issue/PR for a new feature, rather than added to this one.

**Review by jsbrittain — COMMENTED** [review]
Looks good to me.

**Review by martinjrobins — APPROVED** [review]
thanks @pipliggins, looks good

**Comment by martinjrobins** [comment]
@all-contributors please add @pipliggins  for code and test

**Pull request merged**
