### PR TITLE
Removing testcase.py file

### PR DESCRIPTION
**Pull request by prady0t**
# Description

Reverting back changes from PR #2844. We are using pytest fixtures now to solve this. Once #4180 gets merged, we can merge this as well.

Fixes # (issue)

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [ ] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by prady0t** [comment]
Converting it to draft until the other PR gets merged.

**Comment by prady0t** [comment]
@agriyakhetarpal I think this is ready to reviewed. Do let me know if I forgot anything.

**Review by agriyakhetarpal — APPROVED** [review]
Thanks, @prady0t! Have you stress-tested this locally?

**Comment by prady0t** [comment]
> Thanks, @prady0t! Have you stress-tested this locally?

Yes. I remember running it overnight. I got no errors.

**Comment by agriyakhetarpal** [comment]
Great, I ran this multiple times as well, albeit not as much as you might have. Nice work!

**Pull request merged**
