### PR TITLE
V24.5

### PR DESCRIPTION
**Pull request by Saransh-cpp**
# Description

Release update for the develop branch

### CODE REVIEW

**Comment by agriyakhetarpal** [comment]
Triggered another deployment after the last commit: https://github.com/pybamm-team/PyBaMM/actions/runs/9668643828, cancelling the tests here for now

**Comment by agriyakhetarpal** [comment]
Oops, I updated the tag but I missed pushing the tag 😅 I don't think the workflow ran at all because it was stuck in the queue, I cancelled it just now. I think I will let you do it because I am about to log off

**Comment by kratman** [comment]
> Oops, I updated the tag but I missed pushing the tag 😅 I don't think the workflow ran at all because it was stuck in the queue, I cancelled it just now. I think I will let you do it because I am about to log off

Yeah I already triggered the correct one. Hopefully you did not cancel mine

**Comment by agriyakhetarpal** [comment]
I think I didn't, it's still running: https://github.com/pybamm-team/PyBaMM/actions/runs/9668726233

**Comment by kratman** [comment]
Tests and deployment passed except for lychee

**Review by agriyakhetarpal — APPROVED** [review]

**Comment by Saransh-cpp** [comment]
Merging this

**Pull request merged**
