### PR TITLE
Bug fix: Make examples more compatible with Mac

### PR DESCRIPTION
**Pull request by kratman**
# Description

Fixing some issues in the notebooks that caused failures on MacOS and in Nox sessions.

Changes:
- Changed ```%pip install pybamm[plot,cite] -q``` to ```%pip install "pybamm[plot,cite]" -q``` in the notebooks. This prevents failures on MacOS.
- Fixed the temporary file name in the quick plot function create_gif() function. Running ```nox -s examples``` had failures due to "file not found" errors. The function would use the same file names on different threads creating a race condition.
- Fixed the link to keras' callbacks.py file. The files moved and the link no longer functioned.

## Type of change

Minor bug fixes in the notebooks.

- [x] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [x] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by kratman** [comment]
This will likely cause conflicts with #3372, but I will fix them if that happens.

**Comment by kratman** [comment]
It looks like keras moved the callbacks.py script. The link no longer works and was detected by Lychee. I can push a fix for that too if it helps this pass.

**Comment by kratman** [comment]
Broken link fixed. Can this be re-triggered for CI?

**Review by Saransh-cpp — APPROVED** [review]
Thanks, @kratman! Could you merge develop once and fix the merge conflicts? The broken link has been fixed in develop.

**Comment by kratman** [comment]
@Saransh-cpp done

**Comment by Saransh-cpp** [comment]
@kratman could you please also edit the relevant tests to ensure this does not happen in the future? Setting `output_filename` in the tests should be good!

https://github.com/pybamm-team/PyBaMM/blob/fc570af4999274e90cc9ce356be58476be16f779/tests/unit/test_plotting/test_quick_plot.py#L292-L296

**Comment by kratman** [comment]
> @kratman could you please also edit the relevant tests to ensure this does not happen in the future? Setting `output_filename` in the tests should be good!
> 
> https://github.com/pybamm-team/PyBaMM/blob/fc570af4999274e90cc9ce356be58476be16f779/tests/unit/test_plotting/test_quick_plot.py#L292-L296

I will make that change as well. I think the tests should write to temporary directories though. I notice that the tests leave a lot of files behind when I run them.

**Comment by Saransh-cpp** [comment]
That sounds great, thanks again, @kratman! 🙂

**Pull request merged**
