### PR TITLE
Removed pybtex warnings on downstream projects

### LINKED ISSUE #4304: Pybtex warnings on downstream projects
When importing projects which use PyBaMM (e.g. pybamm-eis) users can get the following warning:
```
>>> import pybammeis
2024-07-29 18:14:25.383 - [WARNING] citations.read_citations(76): Citations could not be read
because the 'pybtex' library is not installed. Install 'pybamm[cite]' to enable citation reading.
```
This warning should probably be removed since it is popping up in other projects

### PR DESCRIPTION
**Pull request by 1e9abhi1e10**
# Description

This PR aims to remove the unnecessary citation warning by replacing the warning with a pass statement.

Fixes #4304

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [ ] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by agriyakhetarpal — CHANGES_REQUESTED** [review]
Hi @1e9abhi1e10! Thanks for contributing. I don't think this change is desirable in its current state; we want to keep the warning, but refactor the code so that it appears when one uses the `pybamm.citations` module – and not when PyBaMM is imported (which is the current behaviour).

**Comment by kratman** [comment]
@1e9abhi1e10 if I remember correctly, the real problem is that the citations class has a global instance. So that instance is created whenever pybamm is imported.

That citations object is used in a bunch of places, so either the warning needs to come from another function, or the global instance should be removed

**Comment by valentinsulzer** [comment]
I would suggest we remove the warning from its current location and instead raise an error if the user calls `pybamm.print_citations()` and `pybtex` is not installed.

**Comment by 1e9abhi1e10** [comment]
Thanks for the feedback! I will make changes soon based on your suggestions.

**Comment by agriyakhetarpal** [comment]
Could you fix the merge conflicts, @1e9abhi1e10?

**Comment by kratman** [comment]
@1e9abhi1e10 Are you still working on this or can I take over this PR?

**Comment by 1e9abhi1e10** [comment]
> @1e9abhi1e10 Are you still working on this or can I take over this PR?

Sure, feel free to take over.

**Comment by kratman** [comment]
Thanks, I try not to take over PRs, but I want this in the release that is coming this weekend

**Comment by arjxn-py** [comment]
Thanks for contributing @1e9abhi1e10. 

> Thanks, I try not to take over PRs, but I want this in the release that is coming this weekend

Sounds fair, thanks for taking the initiative @kratman :)

I'm going to close this since it's superseded by #4383

**Pull request closed without merging**
