### PR TITLE
Updated SEI on cracks example

### PR DESCRIPTION
**Pull request by DrSOKane**
# Description

Updated plots in SEI on cracks example notebook to improve visibility

### CODE REVIEW

**Comment by kratman** [comment]
@DrSOKane In the updated notebook, all the lines in the plots sit on top of each other. Is this intended?

**Comment by kratman** [comment]
image

**Comment by kratman** [comment]
Ok I just wanted to make sure since the change was changing the plotting styles, but then the plots also changed

**Comment by DrSOKane** [comment]
> Ok I just wanted to make sure since the change was changing the plotting styles, but then the plots also changed

What happened was the code got changed, but the plots never updated. So now I've re-run the code to get the plots right.

**Review by kratman — APPROVED** [review]

**Pull request merged**
