### PR TITLE
Improve reliability of simulations when using `CasadiSolver`

### LINKED ISSUE #3415: Scheduled tests failing while running example tests on python 3.8 (Ubuntu)
Example tests failing while testing half-cell.ipynb - https://github.com/pybamm-team/PyBaMM/actions/runs/6427005783/job/17452030411#step:15:682

### PR DESCRIPTION
**Pull request by agriyakhetarpal**
# Description

Closes #3415; wraps and calls a fixed random seed set to the name of the `Simulation` class when using the `CasadiSolver` or `CasadiAlgebraicSolver` solvers for a model, which are susceptible to the initial conditions and sometimes fail randomly. This situation has been fixed for the integration tests and for the benchmarks earlier, this PR ensures that it will be fixed for general-purpose use-cases of the `Simulation` class.

Setting a random seed has been shown to bring the failure rate to zero on repeated executions of the half-cell models Jupyter notebook: https://github.com/agriyakhetarpal/PyBaMM/actions/runs/6709408022, https://github.com/agriyakhetarpal/PyBaMM/actions/runs/6729021051.

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [x] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by agriyakhetarpal** [comment]
Since this is a bug fix, should this be included in the release?

**Review by kratman — APPROVED** [review]
Using a hash of the function name seems to be a bit of overkill, but it looks good. The failing integration tests look like they are just a sporadic pip download issue

**Comment by agriyakhetarpal** [comment]
> Using a hash of the function name seems to be a bit of overkill, but it looks good. 

I agree, albeit setting it as such should ensure that the hash will change at a time only when the name of the class changes—which will never happen

**Review by Saransh-cpp — COMMENTED** [review]
I can include this in the next rc release once it is merged in develop.

**Review by Saransh-cpp — APPROVED** [review]
Thanks, @agriyakhetarpal!

**Pull request merged**
