### PR TITLE
Add current collector domains and correct units

### PR DESCRIPTION
**Pull request by darryl-ad**
# Description

Fixes a bug where parameter sets imported from BPX using `create_from_BPX` were incompatible with the "lumped" thermal model. 
- Added current collector domains when assigning thermal properties
- Corrected notation of units from BPX to match PyBaMM
- Assigned arbitrary values for current collector thickness and conductivity

Fixes # [2860](https://github.com/pybamm-team/PyBaMM/issues/2860)

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all`
- [x] The documentation builds: `$ python run-tests.py --doctest`

You can run unit and doctests together at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by RuiheLi** [comment]
Thanks @darryl-ad  That is really quick! I just went through your changes and they make sense to me. 

Also really appreciate your suggestion. I am still learning to become a maintainer tbh. I will look into your suggestion in the next few days and see how to improve this a bit further.

**Review by rtimms — COMMENTED** [review]
thanks @darryl-ad looks good! could you add a default for the heat transfer like you suggested on the issue and also add an entry to the [changelog](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) please?

could you also open an issue on the [bpx repo](https://github.com/pybamm-team/BPX) to fix the units? (and fix it if you have time haha)

**Comment by darryl-ad** [comment]
@rtimms done!

I changed my mind on the BPX repo code. The units are defined as [J.K-1.kg-1] in the schema, so the BPX code is correct and a conversion is required within PyBAMM

**Review by rtimms — APPROVED** [review]
thanks! yeah good point, let's keep BPX consistent with the schema

**Comment by rtimms** [comment]
@all-contributors please add @darryl-ad for code and bug report

**Comment by rtimms** [comment]
The failing notebook is unrelated to this PR and will be fixed as part of #2957

**Pull request merged**
