### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by agriyakhetarpal**
# Description

Fixes a minor typo in the [docs](https://pybamm.readthedocs.io/en/latest/install/install-from-source.html#running-the-tests)

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ flake8`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by Saransh-cpp — COMMENTED** [review]
Maybe we can add a pre-commit to detect typos? Something like this -
```yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        args: ["-L", "{add false positives here separated by comma - pybamm,dfn,spm,...}"]
```

**Comment by agriyakhetarpal** [comment]
I'll be glad to add it, @Saransh-cpp! Would you prefer it as a separate PR?

**Comment by tinosulzer** [comment]
Would the spell check have caught this case ("is" is a valid word)? I think it might be overkill with way too many exceptions

**Comment by agriyakhetarpal** [comment]
That's right, it's more of a grammatical error rather than a typo – `codespell` has the potential to cause some problems with triggering certain function names in [some](https://github.com/matplotlib/matplotlib/issues/22740/) repositories

**Comment by Saransh-cpp** [comment]
> codespell has the potential to cause https://github.com/matplotlib/matplotlib/issues/22740/ problems with triggering certain function names in some repositories

I don't understand the reference here (the issue talks about adding `codespell` to `matplotlib`?), but yes, as @tinosulzer mentioned, `codespell` might be overkill (and we might end up maintaining a long list of false positives).

Thanks for fixing this! 😄

**Comment by tinosulzer** [comment]
@all-contributors add @agriyakhetarpal for infra

**Pull request merged**
