### PR TITLE
Fix KLU not installed error in validation repository

### PR DESCRIPTION
**Pull request by Vaibhav-Chopra-GT**
# Description

I tried everything, but installing pybamm in GitHub Actions using `pip` always throws the `KLU not installed` error.  I tried creating a separate tox file (as that works for pybamm right now) for the validation repository, but it still did not work. A simple fix for this was to keep the scripts inside the pybamm repository, clone pybamm in validation repository's workflow, and run the scripts in pybamm's tox environment.  

I have made the required changes in this PR, and the workflows are passing here - https://github.com/Vaibhav-Chopra-GT/test-pybamm/actions/runs/3032880848

Fixes # (issue)

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ flake8`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by tinosulzer — COMMENTED** [review]
Very strange that it works in pybamm's github actions but not in pybamm-validation. @priyanshuone6 @Saransh-cpp any ideas why that is?

Otherwise, changes look good. If we go down the road of having the benchmarking scripts still in the pybamm repo, we should link to where they are in pybamm-validation

**Comment by Saransh-cpp** [comment]
This is weird. I created a minimal example - https://github.com/Saransh-cpp/pybamm-idaklusolver-test/blob/main/.github/workflows/ci.yml - and it indeed does not work - https://github.com/Saransh-cpp/pybamm-idaklusolver-test/actions/runs/3115076483/jobs/5051607653

Maybe @martinjrobins can help?

**Comment by tinosulzer** [comment]
@Saransh-cpp can you try your workflow with the branch `idaklu-install-debug`?

**Comment by Saransh-cpp** [comment]
The [workflow](https://github.com/Saransh-cpp/pybamm-idaklusolver-test/actions/runs/3115467411/jobs/5052389760) outputs -
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/hostedtoolcache/Python/3.9.[14](https://github.com/Saransh-cpp/pybamm-idaklusolver-test/actions/runs/3115467411/jobs/5052389760#step:8:15)/x64/lib/python3.9/site-packages/pybamm/solvers/idaklu_solver.py", line 59, in __init__
    raise ImportError(f"KLU is not installed: {idaklu_spec}")
ImportError: KLU is not installed: Could not import idaklu module
```

**Comment by tinosulzer** [comment]
Can you run again? Just changed it so it saves the ImportError message

**Comment by Saransh-cpp** [comment]
A missing file?
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/hostedtoolcache/Python/3.9.[14](https://github.com/Saransh-cpp/pybamm-idaklusolver-test/actions/runs/3115508691/jobs/5052473330#step:8:15)/x64/lib/python3.9/site-packages/pybamm/solvers/idaklu_solver.py", line 59, in __init__
    raise ImportError(f"KLU is not installed: {idaklu_spec}")
ImportError: KLU is not installed: Could not import idaklu module: libsundials_sunmatrixsparse.so.3: cannot open shared object file: No such file or directory
```

**Comment by tinosulzer** [comment]
Could be an issue with `LD_LIBRARY_PATH` (see [here](https://www.baeldung.com/linux/solve-shared-object-error#the-ldlibrarypath-variable))

This is set by `tox.ini` in pybamm: https://github.com/pybamm-team/PyBaMM/blob/f5d16bc424af09bc0b4c0879801cbe7d88bf4807/tox.ini#L27

**Comment by tinosulzer** [comment]
Having said that: since we are moving to a monorepo (#2315 ) we should just do all this in a new folder `validation` in this repo

**Comment by Saransh-cpp** [comment]
Adding the missing env variables worked!

The passing workflow - https://github.com/Saransh-cpp/pybamm-idaklusolver-test/actions/runs/3137300340
`YAML` file - https://github.com/Saransh-cpp/pybamm-idaklusolver-test/blob/main/.github/workflows/ci.yml

@Vaibhav-Chopra-GT, you can set the required variables in validation repository's workflows and then move all the related benchmarks there -
```yaml
    - name: Clone PyBaMM
      run: |
        python -m pip install wheel
        git clone -b develop --single-branch https://github.com/pybamm-team/PyBaMM
    - name: Install casadi cmake numpy
      run: python -m pip install cmake casadi numpy
    - name: Install Sundials, KLU, and clone pybind11
      run: |
        pip install wget
        cd PyBaMM
        python ./scripts/install_KLU_Sundials.py
        git clone https://github.com/pybind/pybind11.git ./pybind11
    - name: Set env variables and install PyBaMM
      run: |
        echo "SUNDIALS_INST=$HOME/.local" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$HOME/.local/lib" >> $GITHUB_ENV
        cd PyBaMM
        python -m pip install . 
    - name: Test
      run: python -c "import pybamm; pybamm.IDAKLUSolver()"
```

**Pull request closed without merging**
