### PR TITLE
Build and publish python sdist on PyPI

### PR DESCRIPTION
**Pull request by priyanshuone6**
# Description

Add a workflow to build and publish PyBaMM's python source distribution on PyPI for Windows (.zip) and Unix (.tar.gz)

### CODE REVIEW

**Comment by priyanshuone6** [comment]
Not sure on how to test this

**Comment by tinosulzer** [comment]
What's the difference between this and the existing workflow to publish releases?

**Comment by priyanshuone6** [comment]
A source distribution is basically an archive containing the source code (both Python and C++). In contrast a wheel is what we call a built distribution: it contains the "installed" version of a package - particularly the compiled extension modules.
I talked with @tlestang and he suggested creating a build_sdist.yml that builds the tar.gz and publishes it to PyPI. The tar.gz file published to PyPI will then be used to automatically bump the version on conda-forge/pybamm-feedstock

**Comment by tinosulzer** [comment]
Ok, I don't know how to test this either, I guess @tlestang should review it

**Comment by tlestang** [comment]
That all looks very good. @priyanshuone6 to test this, you can trigger this action from your own fork of PyBaMM. The `workflow_dispatch` at the top of the workflow file entry makes it possible to manually trigger the workflow. When doing so, make sure to choose testpypi to upload the sdist to the test pypi server. you'll need to create an account on test.pypi.org first, and save the token on your fork's secret list.

**Comment by priyanshuone6** [comment]
@tinosulzer @tlestang 
I think it's ready to merge now. You can check the test workflow run [here](https://github.com/priyanshuone6/PyBaMM/runs/3564070355?check_suite_focus=true)

**Pull request merged**
