### PR TITLE
try separating unit and integration tests on windows and mac

### PR DESCRIPTION
**Pull request by tinosulzer**
Separate unit and integration tests in Mac and Windows CI for faster failure

### CODE REVIEW

**Review by Saransh-cpp — APPROVED** [review]
Thanks, @tinosulzer! I think we should also edit the [Testing](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#testing)  and [Pre-commit checks](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#pre-commit-checks) sections of `CONTRIBUTING.md` (`quick` -> `unit`).

**Comment by brosaplanella** [comment]
@all-contributors please add @Saransh-cpp for reviewing PRs

**Comment by brosaplanella** [comment]
@all-contributors please add @Saransh-cpp for reviewing pull requests

**Comment by brosaplanella** [comment]
@all-contributors please add @Saransh-cpp for review

**Pull request merged**
