### PR TITLE
Update BPX version and make PyBaMM compatible with Pydantic V2

### PR DESCRIPTION
**Pull request by kratman**
# Description

BPX switched to Pydantic V2 and the switch causes some breaking changes in PyBaMM

# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python -m pytest` (or `$ nox -s tests`)
- [x] The documentation builds: `$ python -m pytest --doctest-plus src` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ nox -s quick`.

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by kratman** [comment]
I expect this to fail until the new BPX release is available. I tested this locally with the BPX release candidate

**Review by rtimms — DISMISSED** [review]

**Comment by kratman** [comment]
@rtimms Can you re-review this?

**Comment by kratman** [comment]
@agriyakhetarpal Could your review this as well? It was approved before and the BPX parts pass tests already

**Comment by agriyakhetarpal** [comment]
Sure, I will do it tomorrow – thanks!

**Review by rtimms — APPROVED** [review]

**Pull request merged**
