### PR TITLE
Issue #2804 Updated `.readthedocs.yml` to `.readthedocs.yaml`

### LINKED ISSUE #2804: python.version and .readthedocs.yml are deprecated
Use `build.tools.python` and `.readthedocs.yaml` instead — ([1](https://docs.readthedocs.io/en/stable/config-file/v2.html#python-version),[2](https://docs.readthedocs.io/en/stable/config-file/index.html#configuration-file))

This does not break the build, but should be an easy fix for anyone who may want to take it up

### PR DESCRIPTION
**Pull request by arjxn-py**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #2804 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [x] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All tests pass: `$ python run-tests.py --all`
- [x] The documentation builds: `$ python run-tests.py --doctest`

You can run unit and doctests together at once, using `$ python run-tests.py --quick`.

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by Saransh-cpp — COMMENTED** [review]
Thanks, @arjxn-py! Looks good!

One general comment - could you `git cherry-pick` this commit to another branch in your fork and `reset` it from `develop`? It is not a good practice to commit in your fork's `develop` (or default) branch. You will run into problems in the future if you create another PR, or if you pull upstream's `develop` into your local `develop`.

**Comment by arjxn-py** [comment]
@Saransh-cpp I have cherry-picked the changes from develop branch to another branch, now about reset the branch - do I need to open another PR for that or is there some way I can reset the branch in the same PR?

**Comment by Saransh-cpp** [comment]
You might have to create a new PR and close this one. I don't think there is any option to reset the branch.

**Comment by arjxn-py** [comment]
Thanks @Saransh-cpp, I'll do that.

**Pull request closed without merging**
