### PR TITLE
#1886 added fix within processed variable

### LINKED ISSUE #1886: Order of sensitivites
- PyBaMM version - 21.12:
- Python version - 3.8.10:

**Describe the bug**
The order of sensitivities seems to not align correctly when there are multiple sensitivities. The example below shows the sensitivity of terminal voltage SPM to D_n in two cases. Case 1 where only D_n is an input and Case 2 where D_n and b_n (negative electrolyte bruggeman coefficient) are inputs. In Case 2, it appears that the sensitivites of the terminal voltage w.r.t D_n and b_n have been switched. Seems likely a switching of order in either the building of the sensitivity rhs or when extracting from casadi. 

**To Reproduce**
```
import pybamm
import numpy as np
import matplotlib.pyplot as plt

# Case 1
chemistry = pybamm.parameter_sets.Ecker2015
parameter_values = pybamm.ParameterValues(chemistry=chemistry)
parameter_values["Negative electrode diffusivity [m2.s-1]"] = "[input]"

model = pybamm.lithium_ion.SPM()
sim = pybamm.Simulation(model, parameter_values=parameter_values)

inputs = {
    "Negative electrode diffusivity [m2.s-1]": 1e-13,
}

t_eval = np.linspace(0, 30, 1000)
sim.solve(t_eval=t_eval, inputs=inputs, calculate_sensitivities=True)
sol1 = sim.solution


# Case 2
chemistry = pybamm.parameter_sets.Ecker2015
parameter_values = pybamm.ParameterValues(chemistry=chemistry)
parameter_values["Negative electrode diffusivity [m2.s-1]"] = "[input]"
parameter_values["Negative electrode Bruggeman coefficient (electrolyte)"] = "[input]"

model = pybamm.lithium_ion.SPM()
sim = pybamm.Simulation(model, parameter_values=parameter_values)

inputs = {
    "Negative electrode diffusivity [m2.s-1]": 1e-13,
    "Negative electrode Bruggeman coefficient (electrolyte)": 1.5,
}

sim.solve(t_eval=t_eval, inputs=inputs, calculate_sensitivities=True)
sol2 = sim.solution

# Plot
fig, ax = plt.subplots(2, 1, figsize=(16, 9), sharex=True)
ax[0].plot(
    t_eval,
    sol1["Terminal voltage [V]"].sensitivities[
        "Negative electrode diffusivity [m2.s-1]"
    ],
    label="sol1 D_n",
)
ax[0].plot(
    t_eval,
    sol2["Terminal voltage [V]"].sensitivities[
        "Negative electrode diffusivity [m2.s-1]"
    ],
    linestyle="--",
    label="sol2 D_n",
)

ax[1].plot(
    t_eval,
    sol1["Terminal voltage [V]"].sensitivities[
        "Negative electrode diffusivity [m2.s-1]"
    ],
    label="sol1 D_n",
)
ax[1].plot(
    t_eval,
    sol2["Terminal voltage [V]"].sensitivities[
        "Negative electrode Bruggeman coefficient (electrolyte)"
    ],
    linestyle="--",
    label="sol2 b",
)

ax[0].grid()
ax[1].grid()

ax[0].set_xlabel("Time [s]")
ax[1].set_xlabel("Time [s]")

ax[0].legend()
ax[1].legend()

plt.show()
```

**Expected behaviour**
The sensitivity of terminal voltage w.r.t D_n should be independent of the number of other inputs. 

**Screenshots**
Plot generated by above example. 

image

### PR DESCRIPTION
**Pull request by Scottmar93**
# Description

During the solver setup, the list of inputs/sensitivities is sorted by string and then used to assign elements of the y-array to each sensitivity. This applies the same sorting of the list before extracting the sensitivities during the process variables stage. 

I haven't added a test because I couldn't think of a good way without having a full integration test (passing a full model through the pipeline and then checking that the sensitivities are independent of the order of the inputs dictionary). However, I can add it if you think this is worth it for this. 

Fixes #1886 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [X] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [X] No style issues: `$ flake8`
- [X] All tests pass: `$ python run-tests.py --unit`
- [X] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [X] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Review by tinosulzer — APPROVED** [review]
Thanks @Scottmar93 . I checked changing the order in [this test](https://github.com/pybamm-team/PyBaMM/blob/c8a01ba72065a81e3b1c95586361cd76d326adc4/tests/unit/test_solvers/test_casadi_solver.py#L573-L643) and indeed it fails, so it only used to work because p,q,r,s is already sorted. Could you change the order of the sensitivities in the test to make sure it still works with your fix?

**Comment by Scottmar93** [comment]
@tinosulzer ah nice!! Yeah will do!

**Comment by Scottmar93** [comment]
Okay, the original fix passed for some variables but not all so I have just changed it so that the inputs dictionary is sorted straight away upon being passed to the solver. This now passes the test with the dictionary keys in a different order.

**Review by martinjrobins — APPROVED** [review]
thanks @Scottmar93 , this looks good

**Comment by Scottmar93** [comment]
I've tried merging from develop so hopefully that solves the testing issue. It looked like something that was failing on other branches as well though.

**Pull request merged**
