### PR TITLE
Refactor get_initial_stoichiometries with custom and default tolerance

### LINKED ISSUE #3688: Set solver tolerances in ElectrodeSOH classes and methods
Calls to [get_initial_stoichiometries](https://github.com/pybamm-team/PyBaMM/blob/d46cbe3edcf238cdbec09fcfcac8d57e9ca5520b/pybamm/models/full_battery_models/lithium_ion/electrode_soh.py#L851) end up using an [algebraic solver with a fixed tolerance](https://github.com/pybamm-team/PyBaMM/blob/d46cbe3edcf238cdbec09fcfcac8d57e9ca5520b/pybamm/models/full_battery_models/lithium_ion/electrode_soh.py#L726) of 1e-6.

Sometimes this throws an error if the solver tolerance is not met, but users may want to accept a solution with a larger tolerance. It would be good to be able to pass the solver tolerance as an optional argument to `get_initial_stoichiometries` and other places where it is called, e.g. `ParameterValues.set_initial_stoichiometries`.

### PR DESCRIPTION
**Pull request by AlessioBugetti**
# Description

This commit enhances the `get_initial_stoichiometries` method by introducing a new parameter, `solver_tolerance`. The primary change allows users to specify a custom tolerance level for the solver.

The method now includes a default solver tolerance set at 1e-6, maintaining a balance between precision and computational efficiency for general use cases. Additionally, users can adjust this tolerance level as needed, catering to specific requirements of different battery modeling scenarios.

Fixes #3688

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [X] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [X] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [X] All tests pass: `$ python run-tests.py --all` (or `$ nox -s tests`)
- [X] The documentation builds: `$ python run-tests.py --doctest` (or `$ nox -s doctests`)

You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s quick`).

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by agriyakhetarpal** [comment]
Question: should we set the function argument to be just `tol`, instead of `solver_tolerance` – to be in line with that for the `AlgebraicSolver` class?

**Comment by AlessioBugetti** [comment]
I've updated the function argument name from `solver_tolerance` to `tol` in the [latest commit](https://github.com/pybamm-team/PyBaMM/pull/3714/commits/c3ec3b2392d008778b02bdf9761af3ea2ac5e46f). This change brings consistency with the naming convention used in the `AlgebraicSolver` class.

**Review by kratman — APPROVED** [review]
This seems fine to me as long as the tests pass

**Comment by AlessioBugetti** [comment]
I see that the _Run benchmarks on push / benchmarks_ fail, let me know if any changes are required

**Comment by agriyakhetarpal** [comment]
> I see that the _Run benchmarks on push / benchmarks_ fail, let me know if any changes are required or if the PR can be merged

Not to worry, the benchmarks on PRs have always been flaky, and I don't think the changes here can influence them in any way. Let's wait till @rtimms's review as the author of the linked issue, and it should be good to merge after that

**Comment by kratman** [comment]
@AlessioBugetti Can you just add a small summary to the change log?

**Comment by AlessioBugetti** [comment]
> @AlessioBugetti Can you just add a small summary to the change log?

Yes, of course. I have updated the change log as requested.

**Comment by kratman** [comment]
@AlessioBugetti Sorry to do this, but I think it should be in the unreleased section not the RC section for the change log

**Comment by kratman** [comment]
Thanks, just waiting for the tests to pass now

**Pull request merged**
