### PR TITLE
Using posargs to pass tests as arguments to `tests` nox session

### PR DESCRIPTION
**Pull request by prady0t**
# Description

We can now pass specific test names to `tests` session. Example : 
`nox -s test -- tests/unit/test_discretisations/test_discretisation.py` now only runs tests in `test_discretisation.py`

### CODE REVIEW

**Review by Saransh-cpp — APPROVED** [review]

**Review by agriyakhetarpal — COMMENTED** [review]
Thanks, @prady0t! Could you please document this in the Contributing guide?

**Comment by prady0t** [comment]
> Thanks, @prady0t! Could you please document this in the Contributing guide? Edit: also, does this work with a specific test class/case as well, besides a test file?

Yes, it will work with a specific test class/case as well. Let me add documentations.

**Comment by agriyakhetarpal** [comment]
I ran the command, and I think this is a nice improvement for running a selected piece of tests in an isolated virtual environment for local development. That said, it brings a lot of bottlenecks – installing and building PyBaMM is now taking longer than running a bunch of tests :) This might be a good motivator for switching to `uv` (#3825) sometime soon, both for CI and for our `nox` configuration.

**Comment by prady0t** [comment]
I had an eye on that issue and wanted to work on it. Maybe we can also add it to the streach goal?

**Comment by agriyakhetarpal** [comment]
I remember @santacodes working on it some time ago – if he agrees with your proposition, feel free to take over. :) That said, you both can collaborate and work on it together as well if you would like to, either by distributing tasks, preserving co-authorship on commits, or both.

**Comment by prady0t** [comment]
> I remember @santacodes was working on it some time ago – if he agrees with your proposition, feel free to take over. :) That said, you both can collaborate and work on it together as well if you would like to, either by distributing tasks, preserving co-authorship on commits, or both.

That would be nice!

**Comment by santacodes** [comment]
> I remember @santacodes was working on it some time ago – if he agrees with your proposition, feel free to take over. :) That said, you both can collaborate and work on it together as well if you would like to, either by distributing tasks, preserving co-authorship on commits, or both.

Sure, I would love to work with @prady0t, I already had some of the work done on one of my feature branches and then the work was stalled for some time if I remember correctly, I just have to resolve the merge conflicts, and open up a PR.

**Comment by prady0t** [comment]
I've added the documentation. I think this is ready to be merged.

**Review by agriyakhetarpal — APPROVED** [review]

**Review by arjxn-py — APPROVED** [review]

**Comment by arjxn-py** [comment]
This failing randomly [https://github.com/pybamm-team/PyBaMM/actions/runs/10374501121/job/28722081418?pr=4334#step:11:3610](https://github.com/pybamm-team/PyBaMM/actions/runs/10374501121/job/28722081418?pr=4334#step:11:3610)?

**Comment by agriyakhetarpal** [comment]
Yes, seems to be random

**Pull request merged**
