### PR TITLE
Migrate to tox 4.0

### PR DESCRIPTION
**Pull request by Saransh-cpp**
# Description

- A list of breaking changes - https://tox--2601.org.readthedocs.build/en/2601/faq.html#breaking-changes-in-tox-4.
- The relevant issue about env variables not being visible - https://github.com/tox-dev/tox/issues/2659 (macOS tests are probably failing because of this).

Fixes # (issue)

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [ ] No style issues: `$ flake8`
- [ ] All tests pass: `$ python run-tests.py --unit`
- [ ] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by Saransh-cpp** [comment]
macOS looks okay now

**Comment by Saransh-cpp** [comment]
TODO:
- [ ] Dig into `isolated_build` more, which is most probably causing the `ubuntu` tests to fail.
- [ ] Update "tox<4" occurrences with tox

**Comment by tinosulzer** [comment]
@Saransh-cpp feel free to change to `nox` or other if you're more comfortable with it. tox is nice but none of us really know how to maintain it

**Comment by brosaplanella** [comment]
Should we close this PR as we have now #3005 open?

**Comment by Saransh-cpp** [comment]
Yes!

**Pull request closed without merging**
