### PR TITLE
Issue 613 citing

### LINKED ISSUE #613: Citing PyBaMM
Post paper release, add section to README.md (and docs?) on how to cite pybamm

### PR DESCRIPTION
**Pull request by tinosulzer**
# Description

Add citation for pybamm to readme, and add functionality to print citations for the specific parts (models/solvers/parameters) of pybamm that were used when running a simulation

Fixes #613 

## Type of change

Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/master/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the list of breaking changes.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)

# Key checklist:

- [x] No style issues: `$ flake8`
- [x] All tests pass: `$ python run-tests.py --unit`
- [x] The documentation builds: `$ cd docs` and then `$ make clean; make html`

You can run all three at once, using `$ python run-tests.py --quick`.

## Further checks:

- [x] Code is commented, particularly in hard-to-understand areas
- [x] Tests added that prove fix is effective or that feature works

### CODE REVIEW

**Comment by dalonsoa** [comment]
Hi all, 

Relevant to this PR, at Imperial we have created [R2T2](https://imperialcollegelondon.github.io/R2T2/) precisely to cover this functionality. We are in the process of polishing it and making sure it serves the community, but it might be worth have a look at it and - hopefully - implement it :) . It is in PyPI and can be installed as any other dependency. 

Please, have a look at it and let me know if you need some clarification or have any comment. 

Best wishes, 
Diego

**Comment by tinosulzer** [comment]
Looks great! I will change to use that and let you know if I have any questions

**Comment by dalonsoa** [comment]
Reading the references from an external file and including the citations using a Key, which is what you use, is not implemented yet, but that specific functionality was in the backlog, so it might be a good time to implement it if that is the way you want to use it.

**Comment by tinosulzer** [comment]
it wouldn't be too bad, we could just keep the `Citations` class and then call them with `@add_reference("short purpose", pybamm.citations["authorYear"])`. But I'm wondering about testing that the right references are added for each functionality, and also being able to call this from a script (in case people don't like running from command line) - have messaged you on slack, might be quicker to sort out

**Comment by tinosulzer** [comment]
@dalonsoa I am tempted to merge this so we have it for v0.2.0 and then update to use R2T2 when that is ready, would that be ok with you?

**Comment by tinosulzer** [comment]
I assumed that this would be covered by convert_to_casadi but no harm adding it anyway

**Comment by rtimms** [comment]
ah I missed that. yeah should be fine as is then

**Pull request merged**
