### PR TITLE
adding atan

### PR DESCRIPTION
**Pull request by gyouhoc**
# Description

I add atan function in the function.py file. (issue:#972)

Fixes # (issue)

## Type of change

adding arntan function

### CODE REVIEW

**Comment by tinosulzer** [comment]
Thanks for the update - for the test, what I meant was open the file "tests/unit/test_expression_tree/test_functions.py", then add a new function under `test_arcsinh` which does exactly the same thing but for `arctan`. Then run that `test_functions` python script to make sure the test you have added works. Test files should be kept separate from the source code (i.e. you don't need to add the test_functions.py file to `pybamm/expression_tree`, you can just add a single function to the existing test file)

**Comment by gyouhoc** [comment]
Do I run this test file from the prompt? 

python test_fucntion.py gives me following error. 

image

**Comment by tinosulzer** [comment]
You can just run it the way you would run any python file (either from the prompt or through your IDE) - maybe you need to activate your virtual environment?

In the test you added, you should change from `arcsinh` to `arctan` (otherwise it is just a repeat of the test above it).
Also make sure that the style tests pass, you can check this locally by installing flake8 (`pip install flake8`) then running `flake8` from command line - for example, non-empty lines raises an error, which is why this PR says "some checks were not successful"

**Comment by gyouhoc** [comment]
I did flake8 and conduct the test. I have following errors. 

image

**Comment by tinosulzer** [comment]
Make sure you have merged the latest version of the "develop" branch

**Comment by gyouhoc** [comment]
HI Tino, 

Would you let me know how to merge the latest version of the "develop" branch? 
I cloned my branch to my computer. I am a newbie to GitHub.

**Comment by tinosulzer** [comment]
Assuming you have your fork as `origin` and the pybamm repository as `upstream`, the basic command is `git fetch upstream develop`: see [this blog post](https://www.atlassian.com/git/tutorials/git-forks-and-upstreams)

But I downloaded you fork and tried running the test and it works fine for me, so I don't know why you're getting that error

**Comment by gyouhoc** [comment]
can we use your test result for this change?

**Comment by tinosulzer** [comment]
Yes, just replace all occurrences of `arcsinh` with `arctan` in `test_arctan`, and remove the blank spaces from lines 144 and 160 of `test_functions.py` (can you see the error message [here](https://travis-ci.org/github/pybamm-team/PyBaMM/jobs/681142503)?), then we can merge it

**Pull request merged**
